### ISSUE TITLE
Rock: Where is "bot.js"

### ISSUE THREAD

**Issue by Tsunami-Song** [wechaty/puppet-service-providers#10]
[root@iZ2ze python-wechaty-getting-started]
# WECHATY_PUPPET=wechaty-puppet-hostie node bot.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/root/python-wechaty-getting-started/bot.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by jcai** [comment]
You are using python-wechaty,please read some documentation about python-wechaty.

**Comment by huan** [comment]
cc @wj-Mcat
