### ISSUE TITLE
Error: 10 ABORTED: {"code":9999,"msg":"406 NOT_ACCEPTABLE \"fail to add member to group\""}

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-service-providers#13]
With the Rock service, the Friday BOT seems that can not invite developers to our developers home room any more.

The related log messages:

```
16:11:47 VERB Room add(Contact<Huan (李卓桓)>)
16:11:47 VERB PuppetHostie roomAdd(19367909379@chatroom, lizhuohuan)
16:11:48 ERR Config ###########################
16:11:48 ERR Config unhandledRejection: Error: 10 ABORTED: {"code":9999,"msg":"406 NOT_ACCEPTABLE \"fail to add member to group\""}
    at Object.exports.createStatusError (/home/friday/git/friday/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:847:24) [object Promise]
16:11:48 ERR Config ###########################
16:11:48 ERR Config process.on(unhandledRejection) promise.catch(10 ABORTED: {"code":9999,"msg":"406 NOT_ACCEPTABLE \"fail to add member to group\""})
Config Error: 10 ABORTED: {"code":9999,"msg":"406 NOT_ACCEPTABLE \"fail to add member to group\""}
    at Object.exports.createStatusError (/home/friday/git/friday/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 10,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: '{"code":9999,"msg":"406 NOT_ACCEPTABLE \\"fail to add member to group\\""}'
}
(node:19934) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 5)
```

## How to reproduce

Just send `wechaty` to our Friday BOT, then the above error will be triggered.

**Comment by huan** [comment]
Fixed with the help of @jcai

Cheers!

**Comment by huan** [comment]
Link to #20
