### ISSUE TITLE
[BUG]WorkPro:添加好友报异常 Cannot read properties of null (reading 'corpId'

### ISSUE THREAD

**Issue by leesolar** [wechaty/puppet-service-providers#165]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

code is：
> const friend_phone = await bot.Friendship.search({phone: phone})
await bot.Friendship.add(friend_phone, {hello:msg})

exception is:
>  node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);         
 ^
Error: 13 INTERNAL: Cannot read properties of null (reading 'corpId')
    at callErrorFromStatus (/wechatydemo/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/wechatydemo/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/wechatydemo/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/wechatydemo/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /wechatydemo/node_modules/@grpc/grpc-js/build/src/resolving-call.js:93:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/wechatydemo/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
    at ServiceClientImpl.friendshipAdd (/wechatydemo/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:346:12)
    at PuppetService.friendshipAdd (file:///wechatydemo/node_modules/wechaty-puppet-service/dist/esm/src/client/puppet-service.js:1265:44)
    at Function.add (file:///wechatydemo/node_modules/wechaty/dist/esm/src/user-modules/friendship.js:107:39)
    at addFriend (file:///wechatydemo/httpServer.js:233:30) {
  code: 13,
  details: "Cannot read properties of null (reading 'corpId')",
  metadata: Metadata {
    internalRepr: Map(3) {
      'content-type' => [ 'application/grpc+proto' ],
      'date' => [ 'Fri, 13 Jan 2023 10:04:37 GMT' ],
      'authorization' => [ 'Wechaty undefined' ]
    },
    options: {}
  },
  progress: 'PROCESSED'
}

**Info**

 - Platform[e.g. Windows/Mac/Linux]: Linux
 - Runtime version[e.g. node/JAVA]: node
 - Wechaty version:   1.20.2
 - Wechaty Puppet version:  1.19.8

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hcfw007** [comment]
We might need to investigate token log.
Do you have contact juzi.bot? Please send your token and link to this issue to juzi.bot.

**Comment by su-chang** [comment]
@leesolar @hcfw007 该问题已修复，先关闭该issue。
