### ISSUE TITLE
WXWork: 

### ISSUE THREAD

**Issue by choogoo** [wechaty/puppet-service-providers#174]
Please make sure you have read the [Wechaty Puppet Service: WXWork](https://wechaty.js.org/docs/puppet-services/wxwork) from Wechaty Official Website before you continue writting this issue.

## Question

当我获取群组信息的时候报了以下错误导致程序退出

/workspace/wechat-openai-qa-bot/node_modules/@grpc/grpc-js/src/call.ts:81
  const error = new Error(message);
                ^
Error: 13 INTERNAL: WorkproErrorCode: 25032, roomAvatar(10696052604025556) can not get room avatar.
    at callErrorFromStatus (/workspace/wechat-openai-qa-bot/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (/workspace/wechat-openai-qa-bot/node_modules/@grpc/grpc-js/src/client.ts:356:55)
    at Object.onReceiveStatus (/workspace/wechat-openai-qa-bot/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)
    at Object.onReceiveStatus (/workspace/wechat-openai-qa-bot/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
    at /workspace/wechat-openai-qa-bot/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/workspace/wechat-openai-qa-bot/node_modules/@grpc/grpc-js/src/client.ts:326:30)
    at ServiceClientImpl.roomAvatar (/workspace/wechat-openai-qa-bot/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at node:internal/util:364:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:350:12)
    at PuppetService.roomAvatar (file:///workspace/wechat-openai-qa-bot/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:1359:6)
    at WechatifiedUserClass.avatar (file:///workspace/wechat-openai-qa-bot/node_modules/wechaty/src/user-modules/room.ts:1133:32)
    at updateRooms (file:///workspace/wechat-openai-qa-bot/index.ts:432:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 13,
  details: 'WorkproErrorCode: 25032, roomAvatar(10696052604025556) can not get room avatar.',
  metadata: Metadata {
    internalRepr: Map(3) {
      'content-type' => [Array],
      'date' => [Array],
      'authorization' => [Array]
    },
    options: {}
  }
}

**Comment by choogoo** [comment]
定位了10696052604025556这个群是由微信官方创建的 xxx-微信支付服务群，看起来是获取不到这个群的头像导致的报错

**Comment by windmemory** [comment]
@choogoo This is not a Wxwork issue, but a Workpro issue, I've changed the label of this issue, and also the assignees.

Please provide more detailed info so we can better understand the problem, such as how you created this room, what is the code that you are using to get the room info.

**Comment by hcfw007** [comment]
这个错误现在还存在吗？如果存在请联系pin issue上的企微提供一下token，我们排查下日志

**Comment by hcfw007** [comment]
因为长时间没有回复，issue关闭。
