### ISSUE TITLE
[BUG]WorkPro:企业微信无法发送图片，有什么特殊姿势吗

### ISSUE THREAD

**Issue by zhegexiaohuozi** [wechaty/puppet-service-providers#179]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

企业微信无法通过api发送图片，代码如下：
```
    if msg.text() == 'ding':
        await msg.say('dong')
        file_box2 = FileBox.from_url(
            'http://img.wanghaomiao.cn/seimiqq.png',
            name='ding-dong-test2.jpg'
        )
        file_box = FileBox.from_file(
            './tu.jpeg',
            name='ding-dong-test.jpg'
        )
        await msg.say(file_box)
        await msg.say(file_box2)
```
没有收到图片，日志如下：
```
2023-03-01 11:04:35,969 - Wechaty - INFO - receive message <Message#message_type_text[🗣 Contact <1688851869419625> <xxx>    ding>
2023-03-01 11:04:35,970 - Message - INFO - say() <dong>
2023-03-01 11:04:36,429 - FileBox - INFO - init file-box<<class 'wechaty_puppet.file_box.type.FileBoxOptionsUrl'>, ding-dong-test2.jpg>
2023-03-01 11:04:36,439 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
2023-03-01 11:04:36,443 - FileBox - INFO - init file-box<<class 'wechaty_puppet.file_box.type.FileBoxOptionsBase64'>, ding-dong-test.jpg>
2023-03-01 11:04:36,443 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
2023-03-01 11:04:36,443 - Message - INFO - say() <<wechaty_puppet.file_box.file_box.FileBox object at 0x10e42ff70>>
2023-03-01 11:04:36,444 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
2023-03-01 11:04:36,462 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
2023-03-01 11:04:38,912 - Wechaty - INFO - receive <ready> event <EventReadyPayload(data='data ready')>
Exception in callback AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...cdn-2', None)>) at /usr/local/lib/python3.9/site-packages/pyee/asyncio.py:65
handle: <Handle AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...cdn-2', None)>) at /usr/local/lib/python3.9/site-packages/pyee/asyncio.py:65>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/pyee/asyncio.py", line 71, in callback
    self.emit("error", exc)
  File "/usr/local/lib/python3.9/site-packages/wechaty/wechaty.py", line 332, in emit
    return super().emit(event, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyee/base.py", line 179, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/usr/local/lib/python3.9/site-packages/pyee/base.py", line 139, in _emit_handle_potential_error
    raise error
  File "/Users/xx/work/code/PY/python-wechaty-getting-started/examples/ding-dong-bot.py", line 95, in on_message
    await msg.say(file_box)
  File "/usr/local/lib/python3.9/site-packages/wechaty/user/message.py", line 172, in say
    message_id = await self.puppet.message_send_file(
  File "/usr/local/lib/python3.9/site-packages/wechaty_puppet_service/puppet.py", line 373, in message_send_file
    response = await self.puppet_stub.message_send_file(
  File "/usr/local/lib/python3.9/site-packages/wechaty_grpc/wechaty/__init__.py", line 312, in message_send_file
    return await self._unary_unary(
  File "/usr/local/lib/python3.9/site-packages/betterproto/__init__.py", line 1124, in _unary_unary
    response = await stream.recv_message()
  File "/usr/local/lib/python3.9/site-packages/grpclib/client.py", line 425, in recv_message
    await self.recv_initial_metadata()
  File "/usr/local/lib/python3.9/site-packages/grpclib/client.py", line 393, in recv_initial_metadata
    self._raise_for_grpc_status(status, message, details)
  File "/usr/local/lib/python3.9/site-packages/grpclib/client.py", line 345, in _raise_for_grpc_status
    raise GRPCError(status, message, details)
grpclib.exceptions.GRPCError: (<Status.INTERNAL: 13>, 'exec task timeout, queueId: puppet_workpro_xxxxxxx-get-cdn-2', None)
```
**Info**

 - Platform[e.g. Windows/Mac/Linux]: Max
 - Runtime version[e.g. node/JAVA]: Python3.9
 - Wechaty version: 
 - Wechaty Puppet version: 
```
wechaty                0.10.7
wechaty-grpc           0.20.19
wechaty-puppet         0.4.23
wechaty-puppet-service 0.8.10
```

**To Reproduce**

**Expected behavior**

应该可以收到图片

**Screenshots**

**Additional context**

**Comment by su-chang** [comment]
发送图片后调用了stop方法，且这个图片的大小是多少？
```
Mar 1, 2023 @ 11:04:24.106 | info | BaseController | stop: {"token":"="}
```
并且只看到了 ding-dong-test.jpg 这个图片的请求，但是这个fileBox的数据stringify的有点奇怪。影响服务器这边上传素材。

可以试下再用url的方式发送下。并提供对应的发送时间。

**Comment by zhegexiaohuozi** [comment]
> 发送图片后调用了stop方法，且这个图片的大小是多少？
> 
> ```
> Mar 1, 2023 @ 11:04:24.106 | info | BaseController | stop: {"token":"="}
> ```
> 
> 并且只看到了 ding-dong-test.jpg 这个图片的请求，但是这个fileBox的数据stringify的有点奇怪。影响服务器这边上传素材。
> 
> 可以试下再用url的方式发送下。并提供对应的发送时间。

1，这是发送 qr_code日志
```
        qr_code = FileBox.from_qr_code("XXXXX")
        await msg.say(qr_code)
```

```
2023-03-01 15:41:17,034 - Contact - INFO - load contact <Contact <1688851869419625> <XXX>>
2023-03-01 15:41:17,034 - Wechaty - INFO - receive message <Message#message_type_text[🗣 Contact <1688851869419625> <XXX>    ding>
2023-03-01 15:41:17,034 - Message - INFO - say() <dong>
2023-03-01 15:41:17,527 - FileBox - INFO - init file-box<<class 'wechaty_puppet.file_box.type.FileBoxOptionsUrl'>, ding-dong-test2.jpg>
2023-03-01 15:41:17,535 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
2023-03-01 15:41:17,536 - FileBox - INFO - init file-box<<class 'wechaty_puppet.file_box.type.FileBoxOptionsBase64'>, ding-dong-test.jpg>
2023-03-01 15:41:17,536 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
2023-03-01 15:41:17,536 - FileBox - INFO - init file-box<<class 'wechaty_puppet.file_box.type.FileBoxOptionsQrCode'>, qrcode.png>
2023-03-01 15:41:17,536 - Message - INFO - say() <<wechaty_puppet.file_box.file_box.FileBox object at 0x10c8b6b80>>
2023-03-01 15:41:17,536 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
2023-03-01 15:41:17,536 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
Exception in callback AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...cdn-2', None)>) at /usr/local/lib/python3.9/site-packages/pyee/asyncio.py:65
handle: <Handle AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...cdn-2', None)>) at /usr/local/lib/python3.9/site-packages/pyee/asyncio.py:65>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/pyee/asyncio.py", line 71, in callback
    self.emit("error", exc)
  File "/usr/local/lib/python3.9/site-packages/wechaty/wechaty.py", line 332, in emit
    return super().emit(event, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyee/base.py", line 179, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/usr/local/lib/python3.9/site-packages/pyee/base.py", line 139, in _emit_handle_potential_error
    raise error
  File "/Users/xx/work/code/PY/python-wechaty-getting-started/examples/ding-dong-bot.py", line 99, in on_message
    await msg.say(qr_code)
  File "/usr/local/lib/python3.9/site-packages/wechaty/user/message.py", line 172, in say
    message_id = await self.puppet.message_send_file(
  File "/usr/local/lib/python3.9/site-packages/wechaty_puppet_service/puppet.py", line 373, in message_send_file
    response = await self.puppet_stub.message_send_file(
  File "/usr/local/lib/python3.9/site-packages/wechaty_grpc/wechaty/__init__.py", line 312, in message_send_file
    return await self._unary_unary(
  File "/usr/local/lib/python3.9/site-packages/betterproto/__init__.py", line 1124, in _unary_unary
    response = await stream.recv_message()
  File "/usr/local/lib/python3.9/site-packages/grpclib/client.py", line 425, in recv_message
    await self.recv_initial_metadata()
  File "/usr/local/lib/python3.9/site-packages/grpclib/client.py", line 393, in recv_initial_metadata
    self._raise_for_grpc_status(status, message, details)
  File "/usr/local/lib/python3.9/site-packages/grpclib/client.py", line 345, in _raise_for_grpc_status
    raise GRPCError(status, message, details)
grpclib.exceptions.GRPCError: (<Status.INTERNAL: 13>, 'exec task timeout, queueId: puppet_workpro_ecxxx2c-get-cdn-2', None)
```

2，这是发送URL日志
```
        file_box2 = FileBox.from_url(
            'http://img.wanghaomiao.cn/seimiqq.png',
            name='ding-dong-test2.jpg'
        )
        await msg.say(file_box2)
```

```
2023-03-01 15:45:57,405 - Contact - INFO - load contact <Contact <1688851869419625> <XXX>>
2023-03-01 15:45:57,405 - Wechaty - INFO - receive message <Message#message_type_text[🗣 Contact <1688851869419625> <XXX>    ding>
2023-03-01 15:45:57,405 - Message - INFO - say() <dong>
2023-03-01 15:46:02,008 - FileBox - INFO - init file-box<<class 'wechaty_puppet.file_box.type.FileBoxOptionsUrl'>, ding-dong-test2.jpg>
2023-03-01 15:46:02,017 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
2023-03-01 15:46:02,017 - FileBox - INFO - init file-box<<class 'wechaty_puppet.file_box.type.FileBoxOptionsBase64'>, ding-dong-test.jpg>
2023-03-01 15:46:02,018 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
2023-03-01 15:46:02,018 - FileBox - INFO - init file-box<<class 'wechaty_puppet.file_box.type.FileBoxOptionsQrCode'>, qrcode.png>
2023-03-01 15:46:02,018 - Message - INFO - say() <<wechaty_puppet.file_box.file_box.FileBox object at 0x1097c8f40>>
2023-03-01 15:46:02,018 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
2023-03-01 15:46:02,018 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
Exception in callback AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...o url', None)>) at /usr/local/lib/python3.9/site-packages/pyee/asyncio.py:65
handle: <Handle AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...o url', None)>) at /usr/local/lib/python3.9/site-packages/pyee/asyncio.py:65>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/pyee/asyncio.py", line 71, in callback
    self.emit("error", exc)
  File "/usr/local/lib/python3.9/site-packages/wechaty/wechaty.py", line 332, in emit
    return super().emit(event, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyee/base.py", line 179, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/usr/local/lib/python3.9/site-packages/pyee/base.py", line 139, in _emit_handle_potential_error
    raise error
  File "/Users/xx/work/code/PY/python-wechaty-getting-started/examples/ding-dong-bot.py", line 98, in on_message
    await msg.say(file_box2)
  File "/usr/local/lib/python3.9/site-packages/wechaty/user/message.py", line 172, in say
    message_id = await self.puppet.message_send_file(
  File "/usr/local/lib/python3.9/site-packages/wechaty_puppet_service/puppet.py", line 373, in message_send_file
    response = await self.puppet_stub.message_send_file(
  File "/usr/local/lib/python3.9/site-packages/wechaty_grpc/wechaty/__init__.py", line 312, in message_send_file
    return await self._unary_unary(
  File "/usr/local/lib/python3.9/site-packages/betterproto/__init__.py", line 1124, in _unary_unary
    response = await stream.recv_message()
  File "/usr/local/lib/python3.9/site-packages/grpclib/client.py", line 425, in recv_message
    await self.recv_initial_metadata()
  File "/usr/local/lib/python3.9/site-packages/grpclib/client.py", line 393, in recv_initial_metadata
    self._raise_for_grpc_status(status, message, details)
  File "/usr/local/lib/python3.9/site-packages/grpclib/client.py", line 345, in _raise_for_grpc_status
    raise GRPCError(status, message, details)
grpclib.exceptions.GRPCError: (<Status.INTERNAL: 13>, 'no url', None)
```

**Comment by zhegexiaohuozi** [comment]
@su-chang 另外，发本地图 是 60KB，url的你们可以直接抓，qrcode的文本长度大概十几个字，图片大小你们应该也可以估计

**Comment by hcfw007** [comment]
@su-chang 看起来像不同版本之间fileBox url 字段名字不同的问题，Python版的应该挺旧的了

**Comment by su-chang** [comment]
> 可以试下再用url的方式发送下。并提供对应的发送时间。

```
const filebox = FileBox.fromUrl('xxx')
await message.say(filebox)
```

以这种形式可以提供一个案例么？

**Comment by zhegexiaohuozi** [comment]
> > 可以试下再用url的方式发送下。并提供对应的发送时间。
> 
> ```
> const filebox = FileBox.fromUrl('xxx')
> await message.say(filebox)
> ```
> 
> 以这种形式可以提供一个案例么？

@su-chang  有呀，我提供了两个案例，第一个是qr_code，第二个不就是URL的么？

**Comment by zhegexiaohuozi** [comment]
> > 发送图片后调用了stop方法，且这个图片的大小是多少？
> > ```
> > Mar 1, 2023 @ 11:04:24.106 | info | BaseController | stop: {"token":"="}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 并且只看到了 ding-dong-test.jpg 这个图片的请求，但是这个fileBox的数据stringify的有点奇怪。影响服务器这边上传素材。
> > 可以试下再用url的方式发送下。并提供对应的发送时间。
> 
> 1，这是发送 qr_code日志
> 
> ```
>         qr_code = FileBox.from_qr_code("XXXXX")
>         await msg.say(qr_code)
> ```
> 
> ```
> 2023-03-01 15:41:17,034 - Contact - INFO - load contact <Contact <1688851869419625> <XXX>>
> 2023-03-01 15:41:17,034 - Wechaty - INFO - receive message <Message#message_type_text[🗣 Contact <1688851869419625> <XXX>    ding>
> 2023-03-01 15:41:17,034 - Message - INFO - say() <dong>
> 2023-03-01 15:41:17,527 - FileBox - INFO - init file-box<<class 'wechaty_puppet.file_box.type.FileBoxOptionsUrl'>, ding-dong-test2.jpg>
> 2023-03-01 15:41:17,535 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
> 2023-03-01 15:41:17,536 - FileBox - INFO - init file-box<<class 'wechaty_puppet.file_box.type.FileBoxOptionsBase64'>, ding-dong-test.jpg>
> 2023-03-01 15:41:17,536 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
> 2023-03-01 15:41:17,536 - FileBox - INFO - init file-box<<class 'wechaty_puppet.file_box.type.FileBoxOptionsQrCode'>, qrcode.png>
> 2023-03-01 15:41:17,536 - Message - INFO - say() <<wechaty_puppet.file_box.file_box.FileBox object at 0x10c8b6b80>>
> 2023-03-01 15:41:17,536 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
> 2023-03-01 15:41:17,536 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
> Exception in callback AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...cdn-2', None)>) at /usr/local/lib/python3.9/site-packages/pyee/asyncio.py:65
> handle: <Handle AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...cdn-2', None)>) at /usr/local/lib/python3.9/site-packages/pyee/asyncio.py:65>
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "/usr/local/lib/python3.9/site-packages/pyee/asyncio.py", line 71, in callback
>     self.emit("error", exc)
>   File "/usr/local/lib/python3.9/site-packages/wechaty/wechaty.py", line 332, in emit
>     return super().emit(event, *args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/pyee/base.py", line 179, in emit
>     self._emit_handle_potential_error(event, args[0] if args else None)
>   File "/usr/local/lib/python3.9/site-packages/pyee/base.py", line 139, in _emit_handle_potential_error
>     raise error
>   File "/Users/xx/work/code/PY/python-wechaty-getting-started/examples/ding-dong-bot.py", line 99, in on_message
>     await msg.say(qr_code)
>   File "/usr/local/lib/python3.9/site-packages/wechaty/user/message.py", line 172, in say
>     message_id = await self.puppet.message_send_file(
>   File "/usr/local/lib/python3.9/site-packages/wechaty_puppet_service/puppet.py", line 373, in message_send_file
>     response = await self.puppet_stub.message_send_file(
>   File "/usr/local/lib/python3.9/site-packages/wechaty_grpc/wechaty/__init__.py", line 312, in message_send_file
>     return await self._unary_unary(
>   File "/usr/local/lib/python3.9/site-packages/betterproto/__init__.py", line 1124, in _unary_unary
>     response = await stream.recv_message()
>   File "/usr/local/lib/python3.9/site-packages/grpclib/client.py", line 425, in recv_message
>     await self.recv_initial_metadata()
>   File "/usr/local/lib/python3.9/site-packages/grpclib/client.py", line 393, in recv_initial_metadata
>     self._raise_for_grpc_status(status, message, details)
>   File "/usr/local/lib/python3.9/site-packages/grpclib/client.py", line 345, in _raise_for_grpc_status
>     raise GRPCError(status, message, details)
> grpclib.exceptions.GRPCError: (<Status.INTERNAL: 13>, 'exec task timeout, queueId: puppet_workpro_ecxxx2c-get-cdn-2', None)
> ```
> 
> 2，这是发送URL日志
> 
> ```
>         file_box2 = FileBox.from_url(
>             'http://img.wanghaomiao.cn/seimiqq.png',
>             name='ding-dong-test2.jpg'
>         )
>         await msg.say(file_box2)
> ```
> 
> ```
> 2023-03-01 15:45:57,405 - Contact - INFO - load contact <Contact <1688851869419625> <XXX>>
> 2023-03-01 15:45:57,405 - Wechaty - INFO - receive message <Message#message_type_text[🗣 Contact <1688851869419625> <XXX>    ding>
> 2023-03-01 15:45:57,405 - Message - INFO - say() <dong>
> 2023-03-01 15:46:02,008 - FileBox - INFO - init file-box<<class 'wechaty_puppet.file_box.type.FileBoxOptionsUrl'>, ding-dong-test2.jpg>
> 2023-03-01 15:46:02,017 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
> 2023-03-01 15:46:02,017 - FileBox - INFO - init file-box<<class 'wechaty_puppet.file_box.type.FileBoxOptionsBase64'>, ding-dong-test.jpg>
> 2023-03-01 15:46:02,018 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
> 2023-03-01 15:46:02,018 - FileBox - INFO - init file-box<<class 'wechaty_puppet.file_box.type.FileBoxOptionsQrCode'>, qrcode.png>
> 2023-03-01 15:46:02,018 - Message - INFO - say() <<wechaty_puppet.file_box.file_box.FileBox object at 0x1097c8f40>>
> 2023-03-01 15:46:02,018 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
> 2023-03-01 15:46:02,018 - FileBox - WARNING - mimeType will be deprecated after Dec, 2022, we suggest that you should use mediaType property
> Exception in callback AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...o url', None)>) at /usr/local/lib/python3.9/site-packages/pyee/asyncio.py:65
> handle: <Handle AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...o url', None)>) at /usr/local/lib/python3.9/site-packages/pyee/asyncio.py:65>
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "/usr/local/lib/python3.9/site-packages/pyee/asyncio.py", line 71, in callback
>     self.emit("error", exc)
>   File "/usr/local/lib/python3.9/site-packages/wechaty/wechaty.py", line 332, in emit
>     return super().emit(event, *args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/pyee/base.py", line 179, in emit
>     self._emit_handle_potential_error(event, args[0] if args else None)
>   File "/usr/local/lib/python3.9/site-packages/pyee/base.py", line 139, in _emit_handle_potential_error
>     raise error
>   File "/Users/xx/work/code/PY/python-wechaty-getting-started/examples/ding-dong-bot.py", line 98, in on_message
>     await msg.say(file_box2)
>   File "/usr/local/lib/python3.9/site-packages/wechaty/user/message.py", line 172, in say
>     message_id = await self.puppet.message_send_file(
>   File "/usr/local/lib/python3.9/site-packages/wechaty_puppet_service/puppet.py", line 373, in message_send_file
>     response = await self.puppet_stub.message_send_file(
>   File "/usr/local/lib/python3.9/site-packages/wechaty_grpc/wechaty/__init__.py", line 312, in message_send_file
>     return await self._unary_unary(
>   File "/usr/local/lib/python3.9/site-packages/betterproto/__init__.py", line 1124, in _unary_unary
>     response = await stream.recv_message()
>   File "/usr/local/lib/python3.9/site-packages/grpclib/client.py", line 425, in recv_message
>     await self.recv_initial_metadata()
>   File "/usr/local/lib/python3.9/site-packages/grpclib/client.py", line 393, in recv_initial_metadata
>     self._raise_for_grpc_status(status, message, details)
>   File "/usr/local/lib/python3.9/site-packages/grpclib/client.py", line 345, in _raise_for_grpc_status
>     raise GRPCError(status, message, details)
> grpclib.exceptions.GRPCError: (<Status.INTERNAL: 13>, 'no url', None)
> ```

@su-chang  这里第二个就是，且这个URL你们可以直接用来做测试，没有做refer限制

**Comment by su-chang** [comment]
@zhegexiaohuozi typescript版本的wechaty发送图片没有问题。

**Comment by su-chang** [comment]
> @su-chang 看起来像不同版本之间fileBox url 字段名字不同的问题，Python版的应该挺旧的了

@zhegexiaohuozi 你可以检查下python有没有新的版本。

**Comment by zhegexiaohuozi** [comment]
> > @su-chang 看起来像不同版本之间fileBox url 字段名字不同的问题，Python版的应该挺旧的了
> 
> @zhegexiaohuozi 你可以检查下python有没有新的版本。

@su-chang  已经是最新的了，那这个问题，该跟谁反馈？你们不是一个团队？

**Comment by su-chang** [comment]
python-wechaty是由社区维护的，workpro的token是由我们提供支持的。目前我们这边可以确认workpro是支持发送图片的。但是关于python-wechaty相关file-box模块是否正常，这个我们无法确认。可以在python-wechaty的repo中发issue看看是否有人遇到过类似问题？

如果感兴趣，你也可以用node的wechaty试下

**Comment by zhegexiaohuozi** [comment]
> python-wechaty是由社区维护的，workpro的token是由我们提供支持的。目前我们这边可以确认workpro是支持发送图片的。但是关于python-wechaty相关file-box模块是否正常，这个我们无法确认。可以在python-wechaty的repo中发issue看看是否有人遇到过类似问题？
> 
> 如果感兴趣，你也可以用node的wechaty试下

哦，好的，明白了
