### ISSUE TITLE
[BUG]WorkPro: 调用 Room.find() 时报错 invalid roomId

### ISSUE THREAD

**Issue by metanoia1989** [wechaty/puppet-service-providers#182]
**Describe the bug**
账号登录后，调用 bot.Room.find({ topic: 'xxxx' }) 报错，报错信息如下：

```js
unhandledRejection GError: 13 INTERNAL: invalid roomId: 562951801431193
    at callErrorFromStatus (/Users/metanoia/WorkSpace/wechatbot/api/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/Users/metanoia/WorkSpace/wechatbot/api/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/Users/metanoia/WorkSpace/wechatbot/api/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/Users/metanoia/WorkSpace/wechatbot/api/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /Users/metanoia/WorkSpace/wechatbot/api/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/Users/metanoia/WorkSpace/wechatbot/api/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
    at ServiceClientImpl.roomPayload (/Users/metanoia/WorkSpace/wechatbot/api/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at node:internal/util:375:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:361:12)
    at PuppetService.roomRawPayload (file:///Users/metanoia/WorkSpace/wechatbot/api/node_modules/wechaty-puppet-service/dist/esm/src/client/puppet-service.js:932:44)
    at async PuppetService.roomPayload (file:///Users/metanoia/WorkSpace/wechatbot/api/node_modules/wechaty-puppet/dist/esm/src/mixins/room-mixin.js:145:32)
    at async file:///Users/metanoia/WorkSpace/wechatbot/api/node_modules/wechaty-puppet/dist/esm/src/mixins/room-mixin.js:45:32
    at async Promise.all (index 1)
    at async PuppetService.roomSearch (file:///Users/metanoia/WorkSpace/wechatbot/api/node_modules/wechaty-puppet/dist/esm/src/mixins/room-mixin.js:43:40) {
  code: 13,
  details: 'invalid roomId: 562951801431193'
}
```

**Info**

用的dependency：
"wechaty": "^1.20.2",
"wechaty-puppet": "^1.20.1",
"wechaty-puppet-service": "^1.19.8"

找到的是企业微信外部群

**Comment by su-chang** [comment]
这个ID是应用的ID不应该用于查询群聊。这个是主动调用的么？

**Comment by metanoia1989** [comment]
> 这个ID是应用的ID不应该用于查询群聊。这个是主动调用的么？

是主动调用的，调用 `bot.Room.find({ topic: xxx })` 然后报错的。

**Comment by su-chang** [comment]
@metanoia1989 你查询的topic是企业内部的全员群么？

**Comment by metanoia1989** [comment]
> @metanoia1989 你查询的topic是企业内部的全员群么？

查的topic是企业微信外部群，里面有微信成员的。

但是我的企业微信不是公司资质，不知道是不是这个原因。下午我用有公司资质的账号测试一下看看。

**Comment by su-chang** [comment]
嗯 目前看起来这个账号的企业信息是有点异常的。我们这边没有进行兼容。是海外公司么？

**Comment by metanoia1989** [comment]
> 嗯 目前看起来这个账号的企业信息是有点异常的。我们这边没有进行兼容。是海外公司么？

直接微信登录企业微信后，选择创建团队，没有认证的。不是海外公司。

**Comment by metanoia1989** [comment]
> 嗯 目前看起来这个账号的企业信息是有点异常的。我们这边没有进行兼容。是海外公司么？

刚才用企业资质的账号登录，就不会报错了。
