### ISSUE TITLE
[BUG]WorkPro: can not get contact payload by wrong id: R:xxxx

### ISSUE THREAD

**Issue by drjinying** [wechaty/puppet-service-providers#186]
WorkPro 在收到群聊信息时报错崩溃。

path/node_modules/@grpc/grpc-js/src/call.ts:81
  const error = new Error(message);
                ^
GError: 13 INTERNAL: can not get contact payload by wrong id: R:10843810609789812
    at callErrorFromStatus (path/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (path/node_modules/@grpc/grpc-js/src/client.ts:356:55)
    at Object.onReceiveStatus (path/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)
    at Object.onReceiveStatus (path/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
    at path/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (path/node_modules/@grpc/grpc-js/src/client.ts:326:30)
    at ServiceClientImpl.contactPayload (path/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at node:internal/util:364:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:350:12)
    at PuppetService.contactRawPayload (path/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:663:6)
    at async PuppetService.contactPayload (path/node_modules/wechaty-puppet/src/mixins/contact-mixin.ts:298:26)
    at async WechatifiedUserClass.ready (path/node_modules/wechaty/src/user-modules/contact.ts:699:22)
    at async Function.find (path/node_modules/wechaty/src/user-modules/contact.ts:114:9)
    at async PuppetService.<anonymous> (path/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:441:37) {
  code: 13,
  details: 'can not get contact payload by wrong id: R:1084381060978xxxx' // xxxx后四位数字我改成了xxxx
}

重现：

用另一账号（微信账号）创建新群聊，添加workpro登录的企业微信账号，随后使用微信账号发送一条信息。此时workpro登录账号有可能崩溃。
另外，群主转移群主权限给workpro登录的企业微信账号时，企业微信通过获得room的owner依然显示是过去的群主。使用room.sync()尝试刷新，则依然报上述error并崩溃。

**Comment by hcfw007** [comment]
这个是wechaty的bug，可参考 https://github.com/wechaty/wechaty/issues/2410
目前添加error listener来捕获这个错误可以避免崩溃

**Comment by hcfw007** [comment]
因为已经超过一周没有新的回复，issue将被关闭。
