### ISSUE TITLE
[BUG]WorkPro:GError: 13 INTERNAL: can not get contact payload by wrong id: R:10875383514142673

### ISSUE THREAD

**Issue by julyhotter** [wechaty/puppet-service-providers#197]
**Describe the bug**
![Snipaste_2023-04-13_10-37-22](https://user-images.githubusercontent.com/49190978/231633566-8b53e110-5cbc-4110-920b-10b9f1239471.png)

使用微信扫码添加企微机器人，机器人收到加好友请求，接受accept，然后confirm时候选取另一个企微好友，把该好友和微信用户创建一个企微外部群聊，创建成功发送欢迎语后，服务报错，错误信息如下：

**Info**

 - Platform[e.g. Windows/Mac/Linux]: windows
 - Runtime version[e.g. node/JAVA]:node16.16.0
 - Wechaty version: 1.20.2
 - Wechaty Puppet version: "wechaty": "^1.20.2",
    "wechaty-cqrs": "^0.7.5",
    "wechaty-plugin-contrib": "^1.11.1",
    "wechaty-puppet-oicq": "^1.10.2",
    "wechaty-puppet-walnut": "^1.11.6",
    "wechaty-puppet-wechat": "^1.18.1",
    "wechaty-puppet-wechat4u": "~1.11.1",
    "wechaty-puppet-whatsapp": "^1.19.0",
    "wechaty-puppet-xp": "^1.10.20"

**Expected behavior**

创建群聊后不应该报错

D:\WeChaty\getting-started\node_modules\@grpc\grpc-js\src\call.ts:81
  const error = new Error(message);
                ^
GError: 13 INTERNAL: can not get contact payload by wrong id: R:10875383514142673
    at callErrorFromStatus (D:\WeChaty\getting-started\node_modules\@grpc\grpc-js\src\call.ts:81:17)
    at Object.onReceiveStatus (D:\WeChaty\getting-started\node_modules\@grpc\grpc-js\src\client.ts:356:55)
    at Object.onReceiveStatus (D:\WeChaty\getting-started\node_modules\@grpc\grpc-js\src\client-interceptors.ts:455:34)
    at Object.onReceiveStatus (D:\WeChaty\getting-started\node_modules\@grpc\grpc-js\src\client-interceptors.ts:417:48)
    at D:\WeChaty\getting-started\node_modules\@grpc\grpc-js\src\resolving-call.ts:111:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (D:\WeChaty\getting-started\node_modules\@grpc\grpc-js\src\client.ts:326:30)
    at ServiceClientImpl.contactPayload (D:\WeChaty\getting-started\node_modules\@grpc\grpc-js\src\make-client.ts:189:15)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:346:12)
    at PuppetService.contactRawPayload (file:///D:/WeChaty/getting-started/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:663:6)
    at async PuppetService.contactPayload (file:///D:/WeChaty/getting-started/node_modules/wechaty-puppet/src/mixins/contact-mixin.ts:298:26)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by hcfw007** [comment]
这个是wechaty的bug，可参考 https://github.com/wechaty/wechaty/issues/2410。
如果监听了error事件，应该可以捕获到问题继续运行的。
也可以考虑使用@juzi/wechaty来避免这一问题。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
