### ISSUE TITLE
[BUG]WorkPro:发送文件错误

### ISSUE THREAD

**Issue by choogoo** [wechaty/puppet-service-providers#208]
const csv = parse(data, { fields })
  const file = FileBox.fromBuffer(Buffer.from(csv), 'contacts.csv')
  await room.say(file)
  }

报错信息
```
{"id":"R:10792119241893300","payload":{"adminIdList":[],"avatar":"","handle":"wrNfQMBgAASlfWez6wxPPNxuYydRrq3g","id":"R:10792119241893300","memberIdList":["1688850326129606","1688855237333076","7881301094964116","7881302781913704","7881302914943482"],"ownerId":"1688850326129606","topic":"TODO"},"botId":"1688855237333076","_id":"1688855237333076-R:10792119241893300"}
C:\Users\tyutl\Documents\GitHub\easy-chatbots\node_modules\@grpc\grpc-js\src\call.ts:81
  const error = new Error(message);
                ^
Error: 12 UNIMPLEMENTED: [object Object]
    at callErrorFromStatus (C:\Users\tyutl\Documents\GitHub\easy-chatbots\node_modules\@grpc\grpc-js\src\call.ts:81:17)
    at Object.onReceiveStatus (C:\Users\tyutl\Documents\GitHub\easy-chatbots\node_modules\@grpc\grpc-js\src\client.ts:481:55)
    at Object.onReceiveStatus (C:\Users\tyutl\Documents\GitHub\easy-chatbots\node_modules\@grpc\grpc-js\src\client-interceptors.ts:455:34)
    at Object.onReceiveStatus (C:\Users\tyutl\Documents\GitHub\easy-chatbots\node_modules\@grpc\grpc-js\src\client-interceptors.ts:417:48)
    at C:\Users\tyutl\Documents\GitHub\easy-chatbots\node_modules\@grpc\grpc-js\src\resolving-call.ts:111:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeClientStreamRequest (C:\Users\tyutl\Documents\GitHub\easy-chatbots\node_modules\@grpc\grpc-js\src\client.ts:451:30)
    at ServiceClientImpl.messageSendFileStream (C:\Users\tyutl\Documents\GitHub\easy-chatbots\node_modules\@grpc\grpc-js\src\make-client.ts:189:15)
    at response (file:///C:/Users/tyutl/Documents/GitHub/easy-chatbots/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:1911:46)
    at new Promise (<anonymous>)
    at PuppetService.messageSendFileStream (file:///C:/Users/tyutl/Documents/GitHub/easy-chatbots/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:1910:28)
    at async file:///C:/Users/tyutl/Documents/GitHub/easy-chatbots/node_modules/wechaty/src/sayable/deliver-sayable.ts:41:13
    at async WechatifiedUserClass.say (file:///C:/Users/tyutl/Documents/GitHub/easy-chatbots/node_modules/wechaty/src/user-modules/room.ts:496:15)
    at async WechatyImpl.onMessage (file:///C:/Users/tyutl/Documents/GitHub/easy-chatbots/examples/dev2.ts:238:9) {
  code: 12,
  details: '[object Object]',
  metadata: Metadata {
    internalRepr: Map(3) {
      'content-type' => [Array],
      'date' => [Array],
      'authorization' => [Array]
    },
    options: {}
  }
}
PS C:\Users\tyutl\Documents\GitHub\easy-chatbots> ^C
```

**Comment by hcfw007** [comment]
请问你wecahty使用的是什么版本？

**Comment by choogoo** [comment]
> 请问你wecahty使用的是什么版本？

1.20.2

**Comment by hcfw007** [comment]
这个需要加一下客服，提供一下token，我们好看一下日志来排查了。联系客服的方式在置顶issue有。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
