### ISSUE TITLE
[BUG]WorkPro:发送图片报错，业务已经正常运行了几个月了，突然出的问题

### ISSUE THREAD

**Issue by kayorlian** [wechaty/puppet-service-providers#218]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

企业微信 WorkPro 发送文本正常，发送图片报错，业务已经正常运行了几个月了，昨天早上突然出的问题，昨晚恢复后，早上又开始了。

**Info**

 - Platform[e.g. Windows/Mac/Linux]:  Linux
 - Runtime version[e.g. node/JAVA]: node
 - Wechaty version:  1.20.2
 - Wechaty Puppet version:  

**To Reproduce**

1. WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true yarn dev

**Expected behavior**

正常发送图片

**Screenshots**

```
2023-06-21 10:44:09,476 ERROR 46 nodejs.unhandledRejectionError: 12 UNIMPLEMENTED: [object Object]
    at callErrorFromStatus (/dir/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/dir/node_modules/@grpc/grpc-js/build/src/client.js:272:76)
    at Object.onReceiveStatus (/dir/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/dir/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /dir/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeClientStreamRequest (/dir/node_modules/@grpc/grpc-js/build/src/client.js:240:32)
    at ServiceClientImpl.messageSendFileStream (/dir/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at response (/dir/node_modules/wechaty-puppet-service/dist/cjs/src/client/puppet-service.js:1362:52)
    at new Promise (<anonymous>)
    at PuppetService.messageSendFileStream (/dir/node_modules/wechaty-puppet-service/dist/cjs/src/client/puppet-service.js:1361:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /dir/node_modules/wechaty/dist/cjs/src/sayable/deliver-sayable.js:25:17
    at async WechatifiedUserClass.say (/dir/node_modules/wechaty/dist/cjs/src/user-modules/room.js:374:21)
code: 12
details: "[object Object]"
metadata: {"content-type":["application/grpc+proto"],"date":["Wed, 21 Jun 2023 02:44:09 GMT"],"authorization":["Wechaty undefined"]}
name: "unhandledRejectionError"
pid: 46
hostname: c49b6f7c6639

```

**Additional context**

**Comment by su-chang** [comment]
@kayorlian 报错日志有更加详细的上下文信息么？ 目前看服务端没有收到发送消息的请求。

**Comment by su-chang** [comment]
建议提供下发送图片的代码以及对应的素材，也可以试试用其他素材是否能发送成功？

这样可以更快定位问题。

**Comment by kayorlian** [comment]
所有素材都不行。

![test](https://github.com/wechaty/puppet-supports/assets/125865120/e6a08b6e-17ab-4339-a43d-5d1bfcea41ad)

**Comment by kayorlian** [comment]
12 UNIMPLEMENTED


这个错误不是 grpc 那边的问题吗

**Comment by su-chang** [comment]
是的，wechaty-puppet-service中发送图片失败后，会调用一个目前已经deprecated的方法来重试一次。现在这个方法不支持了，所以提示 `12 UNIMPLEMENTED`。

目前要解决这个问题需要知道发送图片的具体报错，看看是哪个层面的问题。

**Comment by kayorlian** [comment]
调用不存在的文件的提示不一样，那这边还需要处理什么

```
2023-06-21 14:36:42,210 ERROR 58393 nodejs.unhandledRejectionError: ENOENT: no such file or directory, stat '/Users/kayorl/proj/gold/lib/../tmp/price__.png'
    at Object.statSync (node:fs:1615:3)
    at new FileBox (/Users/kayorl/proj/gold/node_modules/file-box/dist/cjs/src/file-box.js:376:33)
    at FileBox.fromFile (/Users/kayorl/proj/gold/node_modules/file-box/dist/cjs/src/file-box.js:122:16)
    at Wechat.resolveMessage (/Users/kayorl/proj/gold/lib/wechat.js:141:24)
    at Messenger.<anonymous> (/Users/kayorl/proj/gold/agent.js:33:21)
    at Messenger.emit (node:events:513:28)
    at Messenger._onMessage (/Users/kayorl/proj/gold/node_modules/egg/lib/core/messenger/ipc.js:120:12)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
errno: -2
syscall: "stat"
code: "ENOENT"
path: "/Users/kayorl/proj/gold/lib/../tmp/price__.png"
name: "unhandledRejectionError"
pid: 58393
hostname: kilo.local
```

**Comment by su-chang** [comment]
@kayorlian 这个是本地找不到文件的问题，和服务没有关系。你检查下文件路径是否正确。

**ENOENT: no such file or directory, stat '/Users/kayorl/proj/gold/lib/../tmp/price__.png'**

**Comment by kayorlian** [comment]
> @kayorlian 这个是本地找不到文件的问题，和服务没有关系。你检查下文件路径是否正确。
> 
> **ENOENT: no such file or directory, stat '/Users/kayorl/proj/gold/lib/../tmp/price__.png'**

我测试一个不存在的文件，提示的是这个，测试存在的文件，就是 issue 里的日志。

**Comment by su-chang** [comment]
```
const fileBox = FileBox.fromUrl('文件的URL')
await message.say(fileBox)
```

你用上面这个例子发送文件试试看，可以随便找个url

**Comment by kayorlian** [comment]
> ```
> const fileBox = FileBox.fromUrl('文件的URL')
> await message.say(fileBox)
> ```
> 
> 你用上面这个例子发送文件试试看，可以随便找个url

正常发送

**Comment by su-chang** [comment]
@kayorlian 也就是从本地获取文件无法发送对吗？

**Comment by kayorlian** [comment]
对的

**Comment by su-chang** [comment]
WECHATY_LOG=silly 添加这个环境变量后运行程序，把详细日志打印出来看看。否则不确定问题不好解决。

**Comment by kayorlian** [comment]
```
17:26:51 VERB Message say(FileBox#File<price.png>)
17:26:51 SILL PuppetLoginMixin get currentUserId()
17:26:51 VERB Room say(FileBox#File<price.png>, )
17:26:51 VERB PuppetService messageSendFile(R:10745197564119379, FileBox#File<price.png>)
17:26:51 VERB PuppetService messageSendFile() rejection: 12 UNIMPLEMENTED: The server does not implement the method Upload
2023-06-21 17:26:51,437 ERROR 70059 nodejs.unhandledRejectionError: 12 UNIMPLEMENTED: [object Object]
    at callErrorFromStatus (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/client.js:272:76)
    at Object.onReceiveStatus (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeClientStreamRequest (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/client.js:240:32)
    at ServiceClientImpl.messageSendFileStream (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at response (/Users/kayorl/proj/gold/node_modules/wechaty-puppet-service/dist/cjs/src/client/puppet-service.js:1362:52)
    at new Promise (<anonymous>)
    at PuppetService.messageSendFileStream (/Users/kayorl/proj/gold/node_modules/wechaty-puppet-service/dist/cjs/src/client/puppet-service.js:1361:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/kayorl/proj/gold/node_modules/wechaty/dist/cjs/src/sayable/deliver-sayable.js:25:17
    at async WechatifiedUserClass.say (/Users/kayorl/proj/gold/node_modules/wechaty/dist/cjs/src/user-modules/room.js:374:21)
code: 12
details: "[object Object]"
metadata: {"content-type":["application/grpc+proto"],"date":["Wed, 21 Jun 2023 09:26:51 GMT"],"authorization":["Wechaty undefined"]}
name: "unhandledRejectionError"
pid: 70059
hostname: kilo.local

17:26:51 ERR Config ###########################
17:26:51 ERR Config Wechaty unhandledRejection: Error: 12 UNIMPLEMENTED: [object Object]
    at callErrorFromStatus (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/client.js:272:76)
    at Object.onReceiveStatus (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeClientStreamRequest (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/client.js:240:32)
    at ServiceClientImpl.messageSendFileStream (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at response (/Users/kayorl/proj/gold/node_modules/wechaty-puppet-service/dist/cjs/src/client/puppet-service.js:1362:52)
    at new Promise (<anonymous>)
    at PuppetService.messageSendFileStream (/Users/kayorl/proj/gold/node_modules/wechaty-puppet-service/dist/cjs/src/client/puppet-service.js:1361:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/kayorl/proj/gold/node_modules/wechaty/dist/cjs/src/sayable/deliver-sayable.js:25:17
    at async WechatifiedUserClass.say (/Users/kayorl/proj/gold/node_modules/wechaty/dist/cjs/src/user-modules/room.js:374:21) [object Promise]
17:26:51 ERR Config ###########################
17:26:51 ERR Config process.on(unhandledRejection) promise.catch(12 UNIMPLEMENTED: [object Object])
Config Error: 12 UNIMPLEMENTED: [object Object]
    at callErrorFromStatus (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/client.js:272:76)
    at Object.onReceiveStatus (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeClientStreamRequest (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/client.js:240:32)
    at ServiceClientImpl.messageSendFileStream (/Users/kayorl/proj/gold/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at response (/Users/kayorl/proj/gold/node_modules/wechaty-puppet-service/dist/cjs/src/client/puppet-service.js:1362:52)
    at new Promise (<anonymous>)
    at PuppetService.messageSendFileStream (/Users/kayorl/proj/gold/node_modules/wechaty-puppet-service/dist/cjs/src/client/puppet-service.js:1361:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/kayorl/proj/gold/node_modules/wechaty/dist/cjs/src/sayable/deliver-sayable.js:25:17
    at async WechatifiedUserClass.say (/Users/kayorl/proj/gold/node_modules/wechaty/dist/cjs/src/user-modules/room.js:374:21) {
  code: 12,
  details: '[object Object]',
  metadata: Metadata {
    internalRepr: Map(3) {
      'content-type' => [Array],
      'date' => [Array],
      'authorization' => [Array]
    },
    options: {}
  },
  name: 'unhandledRejectionError'
}
(node:70059) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(Use `node --trace-warnings ...` to show where the warning was created)
17:26:55 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload(len:28)})
17:26:55 SILL PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"regular heartbeat"}"})
17:26:55 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_READY(23), payload(len:21)})
17:26:55 SILL PuppetService onGrpcStreamEvent({type:EVENT_TYPE_READY(23), payload:"{"data":"data ready"}"})
17:26:55 SILL WechatyPuppetMixin __setupPuppetEvents() puppet.on(ready)
```

**Comment by kayorlian** [comment]
12 UNIMPLEMENTED: The server does not implement the method Upload


关键就是这一句了吧。

**Comment by hcfw007** [comment]
服务端是实现了upload的。你用npm ls wechaty-puppet-service看一下版本？

**Comment by kayorlian** [comment]
wechaty-puppet-service@1.19.9

**Comment by kayorlian** [comment]
上班了吗 : )

**Comment by hcfw007** [comment]
上班了，但这个问题太奇怪了，我这边没啥头绪。可以考虑删除node_modules重新安装依赖看看？

**Comment by kayorlian** [comment]
之前已经删过了，我现在也很懵圈

**Comment by kayorlian** [comment]
之前已经删过了，我现在也很懵圈，用的 npmmirror 镜像，这个应该不会影响吧。

**Comment by yangningmoojing** [comment]
我这边也是这个情况，发文字消息可以，文件发不出来，报错，有什么解决办法了吗？

**Comment by hcfw007** [comment]
不会。能否尝试用最小代码复现看看？例如只在ready事件后进行发图片操作？

**Comment by kayorlian** [comment]
> 不会。能否尝试用最小代码复现看看？例如只在ready事件后进行发图片操作？

启动后，隔多久发都一样。

可以考虑一下问题出现的环节： 之前已经稳定运行了很长一段时间，这个问题是突然出现的，而这边涉及到 wechaty 的代码都没碰过，唯一又可能就是删了 yarn.lock 进行了一次重新安装，除此之外，在这几天你们是否做了某些代码的更新升级，导致了这个问题。

**Comment by hcfw007** [comment]
这个问题我复现了，复现了应该就能解决。主要我们线上自己的服务没出这个问题。今天应该能搞定。

**Comment by hcfw007** [comment]
这个找到原因了，我们最近引入了apm来监控性能，与我们原有的框架有些冲突。这个今晚给你更新。由于我们更新是灰度进行的，请 @yangningmoojing 私信客服（在置顶Issue中有）提供一下token吧。

**Comment by su-chang** [comment]
@kayorlian 这个问题已经修复，可以验证下看看.

**Comment by kayorlian** [comment]
已修复，麻烦了
