### ISSUE TITLE
Rock: 被群主从企业微信群中移除，没有对应事件

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-service-providers#22]
```
17:08:56 VERB Room ready()
17:08:56 VERB Puppet dirtyPayload(Room<3>, 9223372041386504059@im.chatroom)
17:08:56 VERB Puppet dirtyPayloadRoom(9223372041386504059@im.chatroom)
17:08:56 VERB Puppet dirtyPayload(RoomMember<4>, 9223372041386504059@im.chatroom)
17:08:56 VERB Puppet dirtyPayloadRoomMember(9223372041386504059@im.chatroom)
17:08:56 VERB PuppetHostie roomMemberList(9223372041386504059@im.chatroom)
17:08:57 VERB Puppet roomPayload(9223372041386504059@im.chatroom)
17:08:57 SILL Puppet roomPayloadCache(9223372041386504059@im.chatroom) cache MISS
17:08:57 VERB PuppetHostie roomRawPayload(9223372041386504059@im.chatroom)
17:08:57 ERR Config ###########################
17:08:57 ERR Config unhandledRejection: Error: 10 ABORTED: {"code":29,"msg":"9223372041386504059@im.chatroom is not room id"}
    at Object.exports.createStatusError (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/client_interceptors.js:847:24) [object Promise]
17:08:57 ERR Config ###########################
17:08:57 ERR Config process.on(unhandledRejection) promise.catch(10 ABORTED: {"code":29,"msg":"9223372041386504059@im.chatroom is not room id"})
Config { Error: 10 ABORTED: {"code":29,"msg":"9223372041386504059@im.chatroom is not room id"}
    at Object.exports.createStatusError (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/client_interceptors.js:847:24)
  code: 10,
  metadata:
   Metadata {
     _internal_repr:
      { 'grpc-accept-encoding': [Array], 'accept-encoding': [Array] },
     flags: 0 },
  details:
   '{"code":29,"msg":"9223372041386504059@im.chatroom is not room id"}' }
17:08:58 VERB PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"heartbeat"}"})
"heartbeat"
```

**Comment by jcai** [comment]
fixed

**Comment by huan** [comment]
I'd like to suggest that we can leave the issue to be open so that the creator can be able to review and close it later.

My recommendation steps are:

1. A issue is filed
1. Someone add a fix to it, and comment the issue so that others can get to know the progress
1. The creator of the issue is notified, then he can confirm whether this issue is solved by test it again:
    1. if the issue is confirmed resolved, then the creator should close the issue, or
    1. if the issue still exists, then the creator can comment the additional information to the issue.

**Comment by su-chang** [comment]
It works now, thank you.
