### ISSUE TITLE
[BUG]WorkPro:扫码登录后要求“在上述设备输入此验证码以登录”

### ISSUE THREAD

**Issue by KroMiose** [wechaty/puppet-service-providers#264]
扫码登录后要求“在上述设备输入此验证码以登录”

**Info**

 - Platform[e.g. Windows/Mac/Linux]: windows / linux
 - Runtime version[e.g. node/JAVA]: node
 - Wechaty version: 1.20.2
 - Wechaty Puppet version: 1.20.2

**To Reproduce**

1. 启动服务进行扫码

**Expected behavior**

手机上点击确认登录后正常登录，或给出提交验证码的回调

**Screenshots**

![image](https://github.com/wechaty/puppet-supports/assets/57167362/e8ab6f77-6621-4589-aa4b-12793d4f6e20)
![image](https://github.com/wechaty/puppet-supports/assets/57167362/b6713b6a-644a-4f0c-a21d-61692fca00aa)

**Additional context**

此现象非100%复现，特定账号可以正常登录，其它账号则会触发验证码输入

**Comment by hcfw007** [comment]
这是企微的新限制，一些账号需要验证码才可以登录。目前需要使用 @juzi/wechaty 包才能输入验证码。稍后我会把文档发出一个Issue。

**Comment by KroMiose** [comment]
好的，感谢回复

**Comment by hcfw007** [comment]
请参考 https://github.com/wechaty/puppet-supports/issues/267

**Comment by lizihao001** [comment]
> 请参考 #267

你好 
日志如下:
10:46:13 INFO PuppetSkeleton start()
10:46:13 INFO PuppetService start() instanciating GrpcManager ...
10:46:13 INFO PuppetService start() instanciating GrpcManager ... done
10:46:13 INFO PuppetService start() setting up bridge grpc event stream ...
10:46:13 INFO PuppetService start() setting up bridge grpc event stream ... done
10:46:13 INFO PuppetService start() starting grpc manager...
10:46:13 WARN last event was 1711622773.979 seconds ago, will not request event cache 
10:46:13 WARN GrpcManager initClient() TLS: disabled (INSECURE)
10:46:13 INFO GrpcManager startStream() connecting event stream with account undefined and seq undefined
/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/subchannel-address.ts:40
  return 'port' in address;
               ^
TypeError: Cannot use 'in' operator to search for 'port' in undefined
    at isTcpSubchannelAddress (/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/subchannel-address.ts:40:16)
    at interleaveAddressFamilies (/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/load-balancer-pick-first.ts:145:27)
    at PickFirstLoadBalancer.updateAddressList (/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/load-balancer-pick-first.ts:533:25)
    at ChildLoadBalancerHandler.updateAddressList (/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/load-balancer-child-handler.ts:137:19)
    at onSuccessfulResolution (/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/resolving-load-balancer.ts:302:34)
    at processTicksAndRejections (node:internal/process/task_queues:85:22)
