### ISSUE TITLE
[BUG]WorkPro:Call cancelled exception

### ISSUE THREAD

**Issue by LLSean** [wechaty/puppet-service-providers#273]
机器人运行一段时间后会报错，但是进程没有退出，无法收到和回复消息，请问是什么原因

GError: 1 CANCELLED: Call cancelled
    at callErrorFromStatus (/shenzuo/running/hmr/bot/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (/shenzuo/running/hmr/bot/node_modules/@grpc/grpc-js/src/client.ts:603:51)
    at Object.onReceiveStatus (/shenzuo/running/hmr/bot/node_modules/@grpc/grpc-js/src/client-interceptors.ts:416:48)
    at /shenzuo/running/hmr/bot/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeServerStreamRequest (/shenzuo/running/hmr/bot/node_modules/@grpc/grpc-js/src/client.ts:586:42)
    at ServiceClientImpl.event (/shenzuo/running/hmr/bot/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at GrpcManager.startStream (file:///shenzuo/running/hmr/bot/node_modules/wechaty-puppet-service/src/client/grpc-manager.ts:298:37)
    at GrpcManager.start (file:///shenzuo/running/hmr/bot/node_modules/wechaty-puppet-service/src/client/grpc-manager.ts:160:16)
    at async PuppetService.onStart (file:///shenzuo/running/hmr/bot/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:173:5)
    at async PuppetService.start (file:///shenzuo/running/hmr/bot/node_modules/state-switch/src/service-ctl/service-ctl.ts:89:9)
    at async PuppetService.start (file:///shenzuo/running/hmr/bot/node_modules/wechaty-puppet/src/mixins/service-mixin.ts:34:7)
    at async PuppetService.start (file:///shenzuo/running/hmr/bot/node_modules/wechaty-puppet/src/mixins/ready-mixin.ts:24:7)
    at async WechatyImpl.start (file:///shenzuo/running/hmr/bot/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:83:11)
    at async WechatyImpl.start (file:///shenzuo/running/hmr/bot/node_modules/state-switch/src/service-ctl/service-ctl.ts:81:11) {
  code: 1,
  details: 'Call cancelled'
}

**Comment by hcfw007** [comment]
这个是grpc与远程服务器连接断开的抛错。需要根据抛错进行合适的重连操作。
可参考 https://github.com/wechaty/puppet-supports/issues/262#issuecomment-1700757876

**Comment by LLSean** [comment]
这个在哪里设置检测呢？exception的地方是在node_modules里

**Comment by hcfw007** [comment]
> 这个在哪里设置检测呢？exception的地方是在node_modules里

需要监听bot的error事件

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
