### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by jimmyjianghz** [wechaty/puppet-service-providers#281]
D:\bigmodel\getting-started\node_modules\ts-node\src\transpilers\swc.ts:262
      throw new Error(
            ^
Error: @swc/core threw an error when attempting to validate swc compiler options.
You may be using an old version of swc which does not support the options used by ts-node.
Try upgrading to the latest version of swc.
Error message from swc:
Failed to deserialize buffer as swc::config::Options
JSON: {"sourceMaps":true,"module":{"noInterop":false,"type":"commonjs","strictMode":true,"ignoreDynamic":false},"swcrc":false,"jsc":{"parser":{"syntax":"typescript","tsx":false,"decorators":true,"dynamicImport":true,"importAssertions":true},"target":"es2022","transform":{"decoratorMetadata":true,"legacyDecorator":true,"react":{"throwIfNamespace":false,"useBuiltins":false}},"keepClassNames":true,"experimental":{"keepImportAssertions":true}}}

Caused by:
    unknown field `keepImportAssertions`, expected one of `plugins`, `keepImportAttributes`, `emitAssertForImportAttributes`, `cacheRoot`, `disableBuiltinTransformsForInternalTesting` at line 1 column 438
    at createVariant (D:\bigmodel\getting-started\node_modules\ts-node\src\transpilers\swc.ts:262:13)
    at createSwcOptions (D:\bigmodel\getting-started\node_modules\ts-node\src\transpilers\swc.ts:211:25)
    at create (D:\bigmodel\getting-started\node_modules\ts-node\src\transpilers\swc.ts:56:41)
    at createTranspiler (D:\bigmodel\getting-started\node_modules\ts-node\src\index.ts:784:16)
    at createTranspileOnlyGetOutputFunction (D:\bigmodel\getting-started\node_modules\ts-node\src\index.ts:1341:28)
    at createFromPreloadedConfig (D:\bigmodel\getting-started\node_modules\ts-node\src\index.ts:1404:34)
    at create (D:\bigmodel\getting-started\node_modules\ts-node\src\index.ts:624:10)
    at register (D:\bigmodel\getting-started\node_modules\ts-node\src\index.ts:591:15)
    at Object.registerAndCreateEsmHooks (D:\bigmodel\getting-started\node_modules\ts-node\src\esm.ts:116:34)
    at file:///D:/bigmodel/getting-started/node_modules/ts-node/esm.mjs:8:7

**Comment by jimmyjianghz** [comment]
安装出现这个问题，需要怎么处理

**Comment by hcfw007** [comment]
"@swc/core": "1.3.39",
锁一下 @swc/core 的版本可以解决

**Comment by jimmyjianghz** [comment]
谢谢

**Comment by chenmingqiang01** [comment]
需要改哪个配置文件，麻烦指导下，十分感谢

**Comment by hcfw007** [comment]
package.json

**Comment by hcfw007** [comment]
长时间未回复，issue关闭。
