### ISSUE TITLE
[BUG]WorkPro:

### ISSUE THREAD

**Issue by AldosdZ** [wechaty/puppet-service-providers#293]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

Please make sure you have read the [Wechaty Puppet Service: WXWork](https://wechaty.js.org/docs/puppet-services/wxwork) from Wechaty Official Website before you continue writting this issue.

## Question
之前一切正常，在一次重启后无论python_wechaty还有RPAChat/workpro-getting-started和juzibot/workpro-getting-started的codespace分别尝试社区和juzibot的发现服务均无法使用机器人，报错分别如下(token替换为puppet_workpro_XXXX)：

python wechaty：

2023-09-22 16:24:14,365 - Wechaty - INFO - initPuppetEventBridge() puppet.on(room-topic) (listenerCount:1) registering...
2023-09-22 16:24:14,365 - Wechaty - INFO - initPuppetEventBridge() puppet.on(scan) (listenerCount:1) registering...
2023-09-22 16:24:14,365 - Wechaty - INFO - starting puppet ...
2023-09-22 16:24:14,365 - PuppetService - INFO - init puppet ...
2023-09-22 16:24:14,365 - PuppetService - INFO - fetching endpoint from chatie-server: https://api.chatie.io/v0/hosties/puppet_workpro_XXXX
Traceback (most recent call last):
  File "/home/ubuntu/chatyenv/lib/python3.10/site-packages/wechaty/wechaty.py", line 445, in start
    await self.puppet.start()
  File "/home/ubuntu/chatyenv/lib/python3.10/site-packages/wechaty_puppet_service/puppet.py", line 911, in start
    self._init_puppet()
  File "/home/ubuntu/chatyenv/lib/python3.10/site-packages/wechaty_puppet_service/puppet.py", line 876, in _init_puppet
    raise WechatyPuppetGrpcError(
wechaty_puppet.exceptions.WechatyPuppetGrpcError: WechatyPuppetGrpcError('can"t fetch endpoint from chatie server. You can try it later, or make sure that your pc can connect to heroku server ', None, None)
STOPPED
2023-09-22 16:24:15,069 - Wechaty - INFO - wechaty is stopping ...
2023-09-22 16:24:15,070 - PuppetService - INFO - stop()
2023-09-22 16:24:15,070 - Wechaty - INFO - wechaty has been stopped gracefully!

![003](https://github.com/wechaty/puppet-supports/assets/127335235/32424afb-c5b4-4e97-a886-8655b8fe786a)

workpro-getting-started：
GError: 14 UNAVAILABLE: Wechaty service discovery / resolution failed for target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_XXXXXab8080: token "puppet_workpro_XXXXX" does not exist
    at callErrorFromStatus (/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/call.ts:82:17)
    at Object.onReceiveStatus (/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/client.ts:360:55)
    at Object.onReceiveStatus (/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
    at Object.onReceiveStatus (/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
    at /workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/resolving-call.ts:132:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/client.ts:325:42)
    at ServiceClientImpl.start (/workspaces/workpro-getting-started/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at node:internal/util:411:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:397:12)
    at GrpcManager.start (/workspaces/workpro-getting-started/node_modules/@juzi/wechaty-puppet-service/src/client/grpc-manager.ts:171:6)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PuppetService.onStart (/workspaces/workpro-getting-started/node_modules/@juzi/wechaty-puppet-service/src/client/puppet-service.ts:163:5)
    at async PuppetService.start (/workspaces/workpro-getting-started/node_modules/state-switch/src/service-ctl/service-ctl.ts:89:9)
    at async PuppetService.start (/workspaces/workpro-getting-started/node_modules/@juzi/wechaty-puppet/src/mixins/service-mixin.ts:34:7) {
  code: 14,
  details: 'Wechaty service discovery / resolution failed for target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_XXXXX: token "puppet_workpro_XXXX" does not exist'

![004](https://github.com/wechaty/puppet-supports/assets/127335235/4598dcfc-17a2-4ad2-b737-f37b2180e574)

**Info**

 - Platform[Linux]: 
 - Runtime version[node/python]:
 - Wechaty version: 
 - Wechaty Puppet version:

**Comment by hcfw007** [comment]
这个是因为发现地址无法找到token。可能的原因是社区发现服务不太稳定，有时候是会出现这种情况的。
我看你使用的是node版本的wechaty，建议你可以提供token后6位，我们帮你切换成私有发现服务，会比较稳定。切换后，使用时需配合 WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com 环境变量使用。

**Comment by AldosdZ** [comment]
token后六位是ab8080，麻烦帮忙处理一下吧

**Comment by AldosdZ** [comment]
> 这个是因为发现地址无法找到token。可能的原因是社区发现服务不太稳定，有时候是会出现这种情况的。 我看你使用的是node版本的wechaty，建议你可以提供token后6位，我们帮你切换成私有发现服务，会比较稳定。切换后，使用时需配合 WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com 环境变量使用。

token后六位是ab8080，麻烦帮忙处理一下吧

**Comment by hcfw007** [comment]
> ab8080

已切换成私有发现服务，请配合环境变量使用。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
