### ISSUE TITLE
Rock: 以 手机号/微信号 添加好友异常

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-service-providers#30]
## 直接添加好友
```
18:32:26 VERB Friendship static add(13126768525, hello, wechat!)
18:32:26 VERB PuppetHostie friendshipAdd(13126768525, hello, wechat!)
18:32:26 ERR Config ###########################
18:32:26 ERR Config unhandledRejection: Error: 10 ABORTED: {"code":1,"msg":"[VerifyUserResponse]vx return code:-2,msg:发送朋友验证失败。","subCode":"-2"}
    at Object.exports.createStatusError (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/client_interceptors.js:847:24) [object Promise]
18:32:26 ERR Config ###########################
18:32:26 ERR Config process.on(unhandledRejection) promise.catch(10 ABORTED: {"code":1,"msg":"[VerifyUserResponse]vx return code:-2,msg:发送朋友验证失败。","subCode":"-2"})
Config { Error: 10 ABORTED: {"code":1,"msg":"[VerifyUserResponse]vx return code:-2,msg:发送朋友验证失败。","subCode":"-2"}
    at Object.exports.createStatusError (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/suchang/Desktop/PROJECT/Test/testDonutCopy/node_modules/grpc/src/client_interceptors.js:847:24)
  code: 10,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details:
   '{"code":1,"msg":"[VerifyUserResponse]vx return code:-2,msg:发送朋友验证失败。","subCode":"-2"}' }
```

## 先搜索，根据搜索结果添加好友，对方没有收到好友请求
```
18:33:54 VERB Friendship static search("{"phone":"13126768525"}")
18:33:54 VERB Puppet friendshipSearch("{"phone":"13126768525"}")
18:33:54 VERB PuppetHostie friendshipSearchPhone(13126768525)
18:33:54 SILL Contact constructor(v3_020b3826fd03010000000000718b05ef7431b4000000501ea9a3dba12f95f6b60a0536a1adb6786d468c0cd49480cabc434f64df7c5df2f18ba148a4f0cc31b54a3896c98b9dfae2bf0fe02f46fd643de4a0@stranger)
18:33:54 SILL Contact ready() @ Puppet#0<PuppetHostie>() with id="v3_020b3826fd03010000000000718b05ef7431b4000000501ea9a3dba12f95f6b60a0536a1adb6786d468c0cd49480cabc434f64df7c5df2f18ba148a4f0cc31b54a3896c98b9dfae2bf0fe02f46fd643de4a0@stranger"
18:33:54 SILL Puppet contactPayload(v3_020b3826fd03010000000000718b05ef7431b4000000501ea9a3dba12f95f6b60a0536a1adb6786d468c0cd49480cabc434f64df7c5df2f18ba148a4f0cc31b54a3896c98b9dfae2bf0fe02f46fd643de4a0@stranger) cache MISS
18:33:54 VERB PuppetHostie contactRawPayload(v3_020b3826fd03010000000000718b05ef7431b4000000501ea9a3dba12f95f6b60a0536a1adb6786d468c0cd49480cabc434f64df7c5df2f18ba148a4f0cc31b54a3896c98b9dfae2bf0fe02f46fd643de4a0@stranger)
18:33:54 SILL Puppet contactPayload(v3_020b3826fd03010000000000718b05ef7431b4000000501ea9a3dba12f95f6b60a0536a1adb6786d468c0cd49480cabc434f64df7c5df2f18ba148a4f0cc31b54a3896c98b9dfae2bf0fe02f46fd643de4a0@stranger) cache SET
search and add friend:13126768525
18:33:55 VERB PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"heartbeat"}"})
"heartbeat"
18:33:55 SILL Wechaty memoryCheck() free: 99 MB, require: 4 MB
18:33:57 VERB PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"heartbeat"}"})
"heartbeat"
18:33:57 SILL Wechaty memoryCheck() free: 42 MB, require: 4 MB
18:33:59 VERB Friendship static add(v3_020b3826fd03010000000000718b05ef7431b4000000501ea9a3dba12f95f6b60a0536a1adb6786d468c0cd49480cabc434f64df7c5df2f18ba148a4f0cc31b54a3896c98b9dfae2bf0fe02f46fd643de4a0@stranger, new friend)
18:33:59 VERB PuppetHostie friendshipAdd(v3_020b3826fd03010000000000718b05ef7431b4000000501ea9a3dba12f95f6b60a0536a1adb6786d468c0cd49480cabc434f64df7c5df2f18ba148a4f0cc31b54a3896c98b9dfae2bf0fe02f46fd643de4a0@stranger, new friend)
```

**Comment by jcai** [comment]
In donut or other  service providers,we can add  friend directly?

**Comment by su-chang** [comment]
User could add friends directly by this way:

```ts
const contact = bot.Contact.load(phone)
await bot.Friendship.add(contact)
```

In donut:
```ts
function add (contact) {
  const searchResult = searchContact(contact.id)
  await addFriendBySearchResult(searchResult)
} 
```

**Comment by huan** [comment]
> bot.Contact.load(phone)

The above method should be treat as a workaround.

The `load()` is not a public API and we should use other way to search contact by phone number.

**Comment by jcai** [comment]
try again!

**Comment by su-chang** [comment]
It works now, thank you.
