### ISSUE TITLE
[BUG]WorkPro:企业token wechaty更换成@juzi/wechaty后启动报错 event.getSeq is not a function

### ISSUE THREAD

**Issue by shijiasen** [wechaty/puppet-service-providers#307]
20:24:32 INFO PuppetSkeleton start()
20:24:32 INFO PuppetService start() instanciating GrpcManager ...
20:24:32 INFO PuppetService start() instanciating GrpcManager ... done
20:24:32 INFO PuppetService start() setting up bridge grpc event stream ...
20:24:32 INFO PuppetService start() setting up bridge grpc event stream ... done
20:24:32 INFO PuppetService start() starting grpc manager...
20:24:32 WARN last event was 1698063872.189 seconds ago, will not request event cache 
20:24:32 INFO getMiscellaneousStoreData() timestamp: undefined, seq: undefined
20:24:32 WARN GrpcManager initClient() TLS: disabled (INSECURE)
20:24:32 INFO GrpcManager startStream() connecting event stream with account undefined and seq undefined
F:\workspace\mitixun-wechaty\node_modules\@juzi\wechaty-puppet-service\src\client\puppet-service.ts:243
    const seq     = event.getSeq()
                          ^
TypeError: event.getSeq is not a function
    at PuppetService.onGrpcStreamEvent (F:\workspace\mitixun-wechaty\node_modules\@juzi\wechaty-puppet-service\src\client\puppet-service.ts:243:27)
    at GrpcManager.emit (node:events:390:28)
    at GrpcManager.emit (node:domain:475:12)
    at GrpcManager.startStream (F:\workspace\mitixun-wechaty\node_modules\@juzi\wechaty-puppet-service\src\client\grpc-manager.ts:409:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GrpcManager.start (F:\workspace\mitixun-wechaty\node_modules\@juzi\wechaty-puppet-service\src\client\grpc-manager.ts:161:5)
    at async PuppetService.onStart (F:\workspace\mitixun-wechaty\node_modules\@juzi\wechaty-puppet-service\src\client\puppet-service.ts:162:5)
    at async PuppetService.start (F:\workspace\mitixun-wechaty\node_modules\@juzi\wechaty-puppet\node_modules\state-switch\src\service-ctl\service-ctl.ts:89:9)
    at async PuppetService.start (F:\workspace\mitixun-wechaty\node_modules\@juzi\wechaty-puppet\src\mixins\service-mixin.ts:34:7)
    at async PuppetService.start (F:\workspace\mitixun-wechaty\node_modules\@juzi\wechaty-puppet\src\mixins\ready-mixin.ts:24:7)

**Comment by su-chang** [comment]
@shijiasen 提供下对应的package.json的信息吧

**Comment by shijiasen** [comment]
> @shijiasen提供下对应的package.json的信息吧

@juzi/wechaty@1.0.74

**Comment by hcfw007** [comment]
请用 npm ls @juzi/wechaty-puppet-service 和 npm ls @juzi/wechaty-grpc 查看一下
然后可以尝试删除 ~/.wechaty 的缓存后重试。

**Comment by shijiasen** [comment]
> 请用 npm ls @juzi/wechaty-puppet-service 和 npm ls @juzi/wechaty-grpc 查看一下 然后可以尝试删除 ~/.wechaty 的缓存后重试。

@juzi/wechaty-puppet-service@1.0.79
@juzi/wechaty-grpc@1.0.68

**Comment by hcfw007** [comment]
> > 请用 npm ls @juzi/wechaty-puppet-service 和 npm ls @juzi/wechaty-grpc 查看一下 然后可以尝试删除 ~/.wechaty 的缓存后重试。
> 
> @juzi/wechaty-puppet-service@1.0.79 @juzi/wechaty-grpc@1.0.68

删除缓存了吗？还是一样的报错？

**Comment by shijiasen** [comment]
> > > 请用 npm ls @juzi/wechaty-puppet-service 和 npm ls @juzi/wechaty-grpc 查看一下 然后可以尝试删除 ~/.wechaty 的缓存后重试。
> > 
> > 
> > @juzi/wechaty-puppet-service@1.0.79 @juzi/wechaty-grpc@1.0.68
> 
> 删除缓存了吗？还是一样的报错？

缓存在哪里看

**Comment by hcfw007** [comment]
> > > > 请用 npm ls @juzi/wechaty-puppet-service 和 npm ls @juzi/wechaty-grpc 查看一下 然后可以尝试删除 ~/.wechaty 的缓存后重试。
> > > 
> > > 
> > > @juzi/wechaty-puppet-service@1.0.79 @juzi/wechaty-grpc@1.0.68
> > 
> > 
> > 删除缓存了吗？还是一样的报错？
> 
> 缓存在哪里看

在 ~/.wechaty，对应 windows 的路径应该是 用户目录/.wechaty

**Comment by shijiasen** [comment]
> > > > > 请用 npm ls @juzi/wechaty-puppet-service 和 npm ls @juzi/wechaty-grpc 查看一下 然后可以尝试删除 ~/.wechaty 的缓存后重试。
> > > > 
> > > > 
> > > > @juzi/wechaty-puppet-service@1.0.79 @juzi/wechaty-grpc@1.0.68
> > > 
> > > 
> > > 删除缓存了吗？还是一样的报错？
> > 
> > 
> > 缓存在哪里看
> 
> 在 ~/.wechaty，对应 windows 的路径应该是 用户目录/.wechaty

清完缓存也不行

**Comment by hcfw007** [comment]
很神奇，可以删除node_modules重新安装依赖试试？另外确保没有 @juzi 前缀的wechaty包都已删除，以免在有些地方错误的引用了。

**Comment by hcfw007** [comment]
暂无回复，Issue关闭。
