### ISSUE TITLE
[BUG]WorkPro: pip如何获取1.x版本 + 扫码后程序闪退如何解决

### ISSUE THREAD

**Issue by ThutmoseAI** [wechaty/puppet-service-providers#310]
**目前使用v0.65版本，网关如下（可正常启动）：**
docker run -ti \
  --name wechaty_puppet_service_token_gateway \
  --rm \
  -e WECHATY_LOG \
  -e WECHATY_PUPPET \
  -e WECHATY_PUPPET_SERVICE_TOKEN \
  -e WECHATY_PUPPET_SERVER_PORT \
  -e WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_SERVER=true \
  -e WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true \
  -e WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com \
  -e WECHATY_TOKEN \
  -p "$WECHATY_PUPPET_SERVER_PORT:$WECHATY_PUPPET_SERVER_PORT" \
  wechaty/wechaty:0.65

**bot运行程序如下：**
options = WechatyOptions(
    port=os.environ.get('port', 8004),
    token="puppet_workpro_b8b9778cd4ee4c8ab196efde852f00xx",
    endpoint="127.0.0.1:8080"
)
bot = Wechaty(options)
bot.use([
    DingDongPlugin(),
    RepeaterPlugin(),
    InfoLoggerPlugin(),
])
asyncio.run(bot.start())

**bot运行后扫码出错：**
03:26:28 INFO IoClient [undefined] https://wx.work.weixin.qq.com/cgi-bin/crtx_auth?key=94C89E8D5808EDCE000E3AC827DAEE31&wx=1
Online QR Code Image: https://wechaty.js.org/qrcode/https%3A%2F%2Fwx.work.weixin.qq.com%2Fcgi-bin%2Fcrtx_auth%3Fkey%3D94C89E8D5808EDCE000E3AC827DAEE31%26wx%3D1
03:26:28 VERB PuppetService onGrpcStreamEvent({type:undefined(33), payload:"{"id":"94C89E8D5808EDCE000E3AC827DAEE31","message":"请输入企业微信手机端展示的验证码，以继续登录","scene":1,"status":1}"})
03:26:28 ERR Config ###########################
03:26:28 ERR Config uncaughtException: Error: eventType 33 unsupported! (code should not reach here)
    at PuppetService.onGrpcStreamEvent (/wechaty/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:578:15)
    at ClientReadableStreamImpl.emit (events.js:400:28)
    at ClientReadableStreamImpl.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at ClientReadableStreamImpl.Readable.push (internal/streams/readable.js:204:10)
    at Object.onReceiveMessage (/wechaty/node_modules/@grpc/grpc-js/src/client.ts:565:16)
    at Object.onReceiveMessage (/wechaty/node_modules/@grpc/grpc-js/src/client-interceptors.ts:383:47)
    at /wechaty/node_modules/@grpc/grpc-js/src/call-stream.ts:346:22
    at processTicksAndRejections (internal/process/task_queues.js:77:11) uncaughtException
03:26:28 ERR Config ###########################
03:27:28 WARN Puppet dogReset() reason: {"data":"onGrpcStreamEvent(undefined)","timeout":60000}
03:27:28 VERB Puppet reset(onGrpcStreamEvent(undefined))
03:27:28 VERB PuppetService stop()

**Comment by ThutmoseAI** [comment]
03:26:28 VERB PuppetService onGrpcStreamEvent({type:undefined(33), payload:"{"id":"94C89E8D5808EDCE000E3AC827DAEE31","message":"请输入企业微信手机端展示的验证码，以继续登录","scene":1,"status":1}"})
03:26:28 ERR Config ###########################
03:26:28 ERR Config uncaughtException: Error: eventType 33 unsupported! (code should not reach here)
    at PuppetService.onGrpcStreamEvent (/wechaty/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:578:15)
    at ClientReadableStreamImpl.emit (events.js:400:28)
    at ClientReadableStreamImpl.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at ClientReadableStreamImpl.Readable.push (internal/streams/readable.js:204:10)
    at Object.onReceiveMessage (/wechaty/node_modules/@grpc/grpc-js/src/client.ts:565:16)
    at Object.onReceiveMessage (/wechaty/node_modules/@grpc/grpc-js/src/client-interceptors.ts:383:47)
    at /wechaty/node_modules/@grpc/grpc-js/src/call-stream.ts:346:22
    at processTicksAndRejections (internal/process/task_queues.js:77:11) uncaughtException
03:26:28 ERR Config ###########################
03:27:28 WARN Puppet dogReset() reason: {"data":"onGrpcStreamEvent(undefined)","timeout":60000}
03:27:28 VERB Puppet reset(onGrpcStreamEvent(undefined))
03:27:28 VERB PuppetService stop()

**Comment by su-chang** [comment]
@ThutmoseAI  企业微信版本升级，workpro的token目前只能使用node版本的wechaty，其他语言还没有进行适配，因此无法使用。
