### ISSUE TITLE
WXWork: 关于exec task timeout

### ISSUE THREAD

**Issue by ing670** [wechaty/puppet-service-providers#316]
Please make sure you have read the [Wechaty Puppet Service: WXWork](https://wechaty.js.org/docs/puppet-services/wxwork) from Wechaty Official Website before you continue writting this issue.

## Question
挂了一个晚上，经常出现如下错误，是什么原因呢？

GError: 13 INTERNAL: exec task timeout, uniqueQueueId: puppet_workpro_72693f4a9ee14b9e9d2a5d771bd359d3-sync-room-id-1970324995036617
    at callErrorFromStatus (G:\ml\workpro-getting-started-latest-features\node_modules\@grpc\grpc-js\build\src\call.js:31:19)
    at Object.onReceiveStatus (G:\ml\workpro-getting-started-latest-features\node_modules\@grpc\grpc-js\build\src\client.js:192:76)
    at Object.onReceiveStatus (G:\ml\workpro-getting-started-latest-features\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:360:141)
    at Object.onReceiveStatus (G:\ml\workpro-getting-started-latest-features\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:323:181)
    at G:\ml\workpro-getting-started-latest-features\node_modules\@grpc\grpc-js\build\src\resolving-call.js:99:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (G:\ml\workpro-getting-started-latest-features\node_modules\@grpc\grpc-js\build\src\client.js:160:32)
    at ServiceClientImpl.roomPayload (G:\ml\workpro-getting-started-latest-features\node_modules\@grpc\grpc-js\build\src\make-client.js:105:19)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:428:12)
    at PuppetService.roomRawPayload (file:///G:/ml/workpro-getting-started-latest-features/node_modules/@juzi/wechaty-puppet-service/dist/esm/src/client/puppet-service.js:1159:44)
    at async PuppetService.roomPayload (file:///G:/ml/workpro-getting-started-latest-features/node_modules/@juzi/wechaty-puppet/dist/esm/src/mixins/room-mixin.js:146:32)
    at async WechatifiedUserClass.ready (file:///G:/ml/workpro-getting-started-latest-features/node_modules/@juzi/wechaty/dist/esm/src/user-modules/room.js:262:24)
    at async WechatifiedRoomImpl.find (file:///G:/ml/workpro-getting-started-latest-features/node_modules/@juzi/wechaty/dist/esm/src/user-modules/room.js:162:17)
    at async WechatifiedUserClass.ready (file:///G:/ml/workpro-getting-started-latest-features/node_modules/@juzi/wechaty/dist/esm/src/user-modules/message.js:880:13) {
  code: 13,
  details: 'exec task timeout, uniqueQueueId: '
}

**Comment by su-chang** [comment]
@ing670 token泄露，麻烦把敏感信息移除。

**Comment by su-chang** [comment]
暂无反馈，关闭该issue。
