### ISSUE TITLE
[BUG]WorkPro: token does not exist

### ISSUE THREAD

**Issue by Wangerya** [wechaty/puppet-service-providers#335]
**Describe the bug**

在本地是好的，部署到服务器报错, 以下配置都加了
Code: add tls: {disable: true} into puppetOptions.
Env: WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true
Env: WECHATY_PUPPET_SERVICE_AUTHORITY= token-service-discovery-test.juzibot.com

**Info**

 - Platform[e.g. Windows/Mac/Linux]: Linux
 - Runtime version[e.g. node/JAVA]: node
 - Wechaty version: 1.0.83
 - Wechaty Puppet version: 1.0.74

 WARN ResolverWechaty updateResolution() address not found target wechaty://token-service-discovery-test.juzibot.com/"puppet_workpro_xxxxxxxxxxxxxxx": token does not exist
Bot 发生错误: GError: 14 UNAVAILABLE: Wechaty service discovery / resolution failed for target wechaty://token-service-discovery-test.juzibot.com/"puppet_workpro_xxxxxxxxxxxxxxx": token ""puppet_workpro_xxxxxxxxxxxxxxx"" does not exist
    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:195:52)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/app/node_modules/@grpc/grpc-js/build/src/client.js:163:34)
    at ServiceClientImpl.start (/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at node:internal/util:441:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:427:12)
    at GrpcManager.start (file:///app/node_modules/@juzi/wechaty-puppet-service/dist/esm/src/client/grpc-manager.js:129:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PuppetService.onStart (file:///app/node_modules/@juzi/wechaty-puppet-service/dist/esm/src/client/puppet-service.js:105:9)
    at async PuppetService.start (file:///app/node_modules/state-switch/dist/esm/src/service-ctl/service-ctl.js:62:17)
    at async PuppetService.start (file:///app/node_modules/@juzi/wechaty-puppet/dist/esm/src/mixins/service-mixin.js:18:13) {
  code: 14,
  details: 'Wechaty service discovery / resolution failed for target wechaty://token-service-discovery-test.juzibot.com/"puppet_workpro_xxxxxxxxxxxxxxx": token ""puppet_workpro_xxxxxxxxxxxxxxx"" does not exist'
}

**Comment by su-chang** [comment]
你配置下这个环境变量试试。
```
WECHATY_SERVICE_DISCOVERY_ENDPOINT=https://token-service-discovery-test.juzibot.com
```

也可以在服务器上访问下
```
curl https://token-service-discovery-test.juzibot.com/v0/hosties/YOUR_TOKEN_HERE
```

**Comment by Wangerya** [comment]
加上可以了，谢谢

**Comment by lizihao001** [comment]
> 加上可以了，谢谢

我想问一下 
![Uploading 1706686861124.png…]()
这是什么原因导致的 
可以分享下他的配置信息嘛
