### ISSUE TITLE
[FEAT]WorkPro: WorkPro有没有Python版本的安装与接入方式?

### ISSUE THREAD

**Issue by dlooto** [wechaty/puppet-service-providers#345]
如题, 你们那个js示例: `https://github.com/wechaty/getting-started`中执行
`npm instal` 总是安装试败, 不是nodejs出问题, 就是其他什么依赖js库. 
在windows,Mac,Ubuntu 这3个不同操作系统下尝试安装, 都没成功.

问: WorkPro是否支持python `pip install -r requirements.txt`的安装及使用方式?

**Comment by dlooto** [comment]
以下是使用windows11下的WSL Ubuntu（windows subsystem for Linux）里面执行安装产生的问题：
```
~/work/repos/getting-started$ npm install
npm ERR! Cannot read property 'insert' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jon/.npm/_logs/2023-12-29T06_34_43_464Z-debug-0.log
jon@Jwin:~/work/repos/getting-started$ npm install cross-env -g
npm ERR! Cannot read property 'insert' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jon/.npm/_logs/2023-12-29T06_37_13_534Z-debug-0.log
```

2023-12-29T06_37_13_534Z-debug-0.log日志文件里面的问题如下：  
```
33 silly placeDep ROOT cross-env@ OK for:  want: *
34 timing idealTree:#root Completed in 194ms
35 timing idealTree:node_modules/cross-env Completed in 0ms
36 timing idealTree:buildDeps Completed in 194ms
37 timing idealTree:fixDepFlags Completed in 1ms
38 timing idealTree Completed in 201ms
39 timing command:install Completed in 206ms
40 verbose stack TypeError: Cannot read property 'insert' of undefined
40 verbose stack     at CacheEntry.store (/usr/share/nodejs/npm/node_modules/make-fetch-happen/lib/cache/entry.js:325:27)
40 verbose stack     at cacheFetch (/usr/share/nodejs/npm/node_modules/make-fetch-happen/lib/cache/index.js:18:18)
40 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
40 verbose stack     at async fetch (/usr/share/nodejs/npm/node_modules/make-fetch-happen/lib/fetch.js:98:7)
40 verbose stack     at async Arborist.[nodeFromEdge] (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1082:19)
40 verbose stack     at async Arborist.[buildDepStep] (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:951:11)
40 verbose stack     at async Arborist.buildIdealTree (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:215:7)
40 verbose stack     at async Arborist.reify (/usr/share/nodejs/@npmcli/arborist/lib/arborist/reify.js:152:5)
40 verbose stack     at async Install.exec (/usr/share/nodejs/npm/lib/commands/install.js:157:5)
40 verbose stack     at async module.exports (/usr/share/nodejs/npm/lib/cli.js:66:5)
41 verbose cwd /home/jon/work/repos/getting-started
42 verbose Linux 5.15.133.1-microsoft-standard-WSL2
43 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "cross-env" "-g"
44 verbose node v12.22.9
45 verbose npm  v8.5.1
46 error Cannot read property 'insert' of undefined
47 verbose exit 1
48 timing npm Completed in 323ms
49 verbose unfinished npm timer reify 1703831833647
50 verbose unfinished npm timer reify:loadTrees 1703831833651
51 verbose code 1
52 error A complete log of this run can be found in:
52 error     /home/jon/.npm/_logs/2023-12-29T06_37_13_534Z-debug-0.log
```

npm/node问题太TM多了， 解决一个又来一个。 你们还是考虑做个其他语言版本的后端吧

**Comment by dlooto** [comment]
Mac下直接被嫌弃Mac OS太老旧、xcode要升级， 即便已经把xcode更到最新： 
```
80-test_cmp_http.t                    (Wstat: 1280 Tests: 6 Failed: 5)
  Failed tests:  1-5
  Non-zero exit status: 5
Files=294, Tests=3562, 753 wallclock secs (16.25 usr  1.54 sys + 422.98 cusr 170.04 csys = 610.81 CPU)
Result: FAIL
make[1]: *** [run_tests] Error 1
make: *** [tests] Error 2

Do not report this issue to Homebrew/brew or Homebrew/homebrew-core!


Error: You are using macOS 10.xx.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.


Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 12.4.
```
OS是没法升级了， 难不成我还要换个Mac本子？

**Comment by dlooto** [comment]
是  企业微信 版的, 不是个人微信

**Comment by billtt** [comment]
看起来有可能是你的node/npm版本太老了？我这边用的是20.10版本的node（直接node官网下载），Mac和Ubuntu都没问题，只是安装npm库的时候有一些warning。

**Comment by hcfw007** [comment]
没有。
理论上，社区版的wechaty提供了Python版本，但实际上这个服务因为缺乏维护，缺少很多基本功能，无法输入验证码。这导致实际上已经不可使用了。
