### ISSUE TITLE
[FEAT]WorkPro:

### ISSUE THREAD

**Issue by crazywu-lab** [wechaty/puppet-service-providers#363]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

We have a token for workpro and updated the `WECHATY_PUPPET_SERVICE_AUTHORITY` to `token-service-discovery-test.juzibot.com`

but still getting following errors

error:
`/Users/charleswu/Workspace/getting-started/node_modules/@grpc/grpc-js/src/subchannel-address.ts:40
  return 'port' in address;
               ^
TypeError: Cannot use 'in' operator to search for 'port' in undefined
    at isTcpSubchannelAddress (/Users/charleswu/Workspace/getting-started/node_modules/@grpc/grpc-js/src/subchannel-address.ts:40:16)
    at interleaveAddressFamilies (/Users/charleswu/Workspace/getting-started/node_modules/@grpc/grpc-js/src/load-balancer-pick-first.ts:145:27)
    at PickFirstLoadBalancer.updateAddressList (/Users/charleswu/Workspace/getting-started/node_modules/@grpc/grpc-js/src/load-balancer-pick-first.ts:520:25)
    at ChildLoadBalancerHandler.updateAddressList (/Users/charleswu/Workspace/getting-started/node_modules/@grpc/grpc-js/src/load-balancer-child-handler.ts:137:19)
    at onSuccessfulResolution (/Users/charleswu/Workspace/getting-started/node_modules/@grpc/grpc-js/src/resolving-load-balancer.ts:298:34)
    at processTicksAndRejections (node:internal/process/task_queues:86:22)`

**Info**

 - Platform[e.g. Windows/Mac/Linux]: Mac
 - Runtime version[e.g. node/JAVA]: node 16.13.0
 - Wechaty version: 1.18.11
 - Wechaty Puppet version: 

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="906" alt="image" src="https://github.com/wechaty/puppet-supports/assets/73957740/516da56f-8f55-40e9-8183-5a7b35c8648c">

**Additional context**

**Comment by su-chang** [comment]
可以使用 https://github.com/RPAChat/workpro-getting-started 这里的案例再测试下看看。

**Comment by su-chang** [comment]
@crazywu-lab 参考这个解决方案：https://github.com/wechaty/puppet-supports/issues/364#issuecomment-1952270004

**Comment by hcfw007** [comment]
无后续反馈，问题关闭。
