### ISSUE TITLE
[BUG]WorkPro:wechaty-puppet-service: WECHATY_PUPPET_SERVICE_TOKEN not found (save token to WECHATY_PUPPET_SERVICE_TOKEN env var or pass it to puppet options is required.).

### ISSUE THREAD

**Issue by sunnyxorange** [wechaty/puppet-service-providers#365]
核对过token正确，在有效期内。但报错

root@RainYun-vpKkeCR4:~# docker logs  workerbot

> worker-assistant@1.0.11 start
> node index.js

2024-02-18 08:10:11 - 使用环境变量中的 aibotkKey 

2024-02-18 08:10:11 - 使用环境变量中的 aibotkSecret 

wechaty-puppet-service: WECHATY_PUPPET_SERVICE_TOKEN not found
(save token to WECHATY_PUPPET_SERVICE_TOKEN env var or pass it to puppet options is required.).

To learn how to get Wechaty Puppet Service Token,
please visit <https://wechaty.js.org/docs/puppet-services/>
to see our Wechaty Puppet Service Providers.

Error: wechaty-puppet-service: WECHATY_PUPPET_SERVICE_TOKEN not found
    at Object.WECHATY_PUPPET_SERVICE_TOKEN (file:///bot/node_modules/@juzi/wechaty-puppet-service/dist/esm/src/env-vars.js:34:11)
    at new PuppetService (file:///bot/node_modules/@juzi/wechaty-puppet-service/dist/esm/src/client/puppet-service.js:59:28)
    at Module.resolvePuppet (file:///bot/node_modules/@juzi/wechaty-puppet/dist/esm/src/puppet/puppet-resolver.js:54:28)
    at async WechatyImpl.init (file:///bot/node_modules/@juzi/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:117:36)
    at async WechatyImpl.init (file:///bot/node_modules/@juzi/wechaty/dist/esm/src/wechaty-mixins/login-mixin.js:50:13)
    at async WechatyImpl.start (file:///bot/node_modules/@juzi/wechaty/dist/esm/src/wechaty/wechaty-base.js:129:9)
npm notice 
npm notice New major version of npm available! 9.6.7 -> 10.4.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
npm notice Run `npm install -g npm@10.4.0` to update!
npm notice

**Comment by su-chang** [comment]
看起来是没有配置对环境变量

**Comment by hcfw007** [comment]
无后续反馈，问题关闭。
