### ISSUE TITLE
[BUG]WorkPro: grpc远端无法拉取正常host在公网的语音文件

### ISSUE THREAD

**Issue by tentacle-pro** [wechaty/puppet-service-providers#368]
之前还是能用的，最近出的问题。
怀疑是grpc远端进行协议解密的架构设计，在拉取语音文件这里设计不良，造成解密服务商的服务器负载高，应该由本地sdk拉取，这样话也不用去找七牛之类的临时托管文件了，本机临时开个服务即可。日志见下：

```
{
  silk_duration: 6,
  silk_url: 'http://luzhua01.tentacle.pro/767c7cce-656c-4b72-92fa-a978eb6d3d86.silk'
}
14:16:13 INFO PuppetService messageSendFile(R:10951889178429173, FileBox#Url<767c7cce-656c-4b72-92fa-a978eb6d3d86.silk>) about to call grpc
/Users/dio/workspace/python/luzhua/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/call.ts:82
  const error = new Error(message);
                ^
Error: 13 INTERNAL: getaddrinfo ENOTFOUND luzhua01.tentacle.pro
    at callErrorFromStatus (/Users/dio/workspace/python/luzhua/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/call.ts:82:17)
    at Object.onReceiveStatus (/Users/dio/workspace/python/luzhua/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/client.ts:360:55)
    at Object.onReceiveStatus (/Users/dio/workspace/python/luzhua/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
    at Object.onReceiveStatus (/Users/dio/workspace/python/luzhua/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
    at /Users/dio/workspace/python/luzhua/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/resolving-call.ts:132:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/Users/dio/workspace/python/luzhua/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/client.ts:325:42)
    at ServiceClientImpl.messageSendFile (/Users/dio/workspace/python/luzhua/api/node_modules/.pnpm/@grpc+grpc-js@1.9.13/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at node:internal/util:430:21
    at new Promise (<anonymous>)
    at bound  (node:internal/util:416:12)
    at PuppetService.messageSendFile (/Users/dio/workspace/python/luzhua/api/node_modules/.pnpm/@juzi+wechaty-puppet-service@1.0.89_@juzi+wechaty-puppet@1.0.79_brolog@1.14.2_redux@4.2.1/node_modules/@juzi/wechaty-puppet-service/src/client/puppet-service.ts:1389:6)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/dio/workspace/python/luzhua/api/node_modules/.pnpm/@juzi+wechaty@1.0.90_@juzi+wechaty-puppet@1.0.79_brolog@1.14.2_redux@4.2.1_rxjs@7.8.1/node_modules/@juzi/wechaty/src/sayable/deliver-sayable.ts:46:13
    at async WechatifiedUserClass.say (/Users/dio/workspace/python/luzhua/api/node_modules/.pnpm/@juzi+wechaty@1.0.90_@juzi+wechaty-puppet@1.0.79_brolog@1.14.2_redux@4.2.1_rxjs@7.8.1/node_modules/@juzi/wechaty/src/user-modules/room.ts:570:15)
    at async chatWithLLMInRoom (/Users/dio/workspace/python/luzhua/api/bot.ts:386:11) {
  code: 13,
  details: 'getaddrinfo ENOTFOUND luzhua01.tentacle.pro',
  metadata: Metadata {
    internalRepr: Map(3) {
      'content-type' => [Array],
      'date' => [Array],
      'authorization' => [Array]
    },
    options: {}
  }
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by su-chang** [comment]
```
getaddrinfo ENOTFOUND luzhua01.tentacle.pro
```
这里提示的地址无法访问，获取不到语音内容就无法发送。可以试试其他域名的链接。

**Comment by tentacle-pro** [comment]
@su-chang 以下文件能直接下载的，测试正常
```
{
  silk_duration: 6,
  silk_url: 'http://luzhua01.tentacle.pro/767c7cce-656c-4b72-92fa-a978eb6d3d86.silk'
}
```
域名在腾讯云的解析正常，cname到七牛的静态文件服务上，本机及其他公网服务器发起下载请求均正常，严重怀疑grpc远端服务器这里有DNS请求的故障

**Comment by su-chang** [comment]
目前看服务端日志都无法识别这个dns的解析，建议换其他图床的链接使用。

**Comment by hcfw007** [comment]
无后续反馈，问题关闭。
