### ISSUE TITLE
运行报如下错误

### ISSUE THREAD

**Issue by whonem** [wechaty/puppet-service-providers#370]
TypeError: Cannot use 'in' operator to search for 'port' in undefined
    at isTcpSubchannelAddress (/Users/lianggao/Documents/code/temp/node_modules/@grpc/grpc-js/build/src/subchannel-address.js:22:19)
    at interleaveAddressFamilies (/Users/lianggao/Documents/code/temp/node_modules/@grpc/grpc-js/build/src/load-balancer-pick-first.js:107:71)
    at PickFirstLoadBalancer.updateAddressList (/Users/lianggao/Documents/code/temp/node_modules/@grpc/grpc-js/build/src/load-balancer-pick-first.js:415:29)
    at ChildLoadBalancerHandler.updateAddressList (/Users/lianggao/Documents/code/temp/node_modules/@grpc/grpc-js/build/src/load-balancer-child-handler.js:115:23)
    at onSuccessfulResolution (/Users/lianggao/Documents/code/temp/node_modules/@grpc/grpc-js/build/src/resolving-load-balancer.js:220:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:85:22)

**Comment by su-chang** [comment]
参考这个：https://github.com/wechaty/puppet-supports/issues/364#issuecomment-1952270004

**Comment by whonem** [comment]
通过了。但扫码后，提示需要在设备上输入验证码

**Comment by sgshy1995** [comment]
> 通过了。但扫码后，提示需要在设备上输入验证码

@whonem 代码示例中有获取验证码的预留位置，动态获取验证码就好了，一共有三次的轮询机会。自己处理这块的逻辑即可。

**Comment by hcfw007** [comment]
无后续反馈，问题关闭。
