### ISSUE TITLE
How to use wechaty / Rock: Error: 14 UNAVAILABLE: DNS resolution failed

### ISSUE THREAD

**Issue by suntong** [wechaty/puppet-service-providers#38]
## Question

How to properly run `wechaty-puppet-rock`?

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

Done.

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

Done.

3. Please search in the issue first, and make sure your problem had not been reported before

Done.

## 1. Versions
- What is your wechaty version? What is your wechaty-puppet-hostie version?

- wechaty@0.51.5
- wechaty-puppet-hostie@0.11.10 and 0.10.8

To be specifically, 

```
├─┬ file-box@0.14.3
├─┬ wechaty@0.51.5
│ ├─┬ wechaty-puppet@0.33.6
│ │ ├─┬ file-box@0.16.2
│ ├─┬ wechaty-puppet-hostie@0.11.10
├─┬ UNMET PEER DEPENDENCY wechaty-puppet@0.32.3
│ ├─┬ file-box@0.13.5
├─┬ wechaty-puppet-hostie@0.10.8
├─┬ wechaty-puppet-mock@0.28.1
└─┬ wechaty-puppet-puppeteer@0.22.1
```

- What is your node version? (run `node --version`)
Answer: `v10.21.0`

- What os are you using

```
$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

## 3. To Reproduce

1. run 'ding-dong-bot.js' from the standard example from wechaty-getting-started

## 4. Expected behavior

It works.

## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show full  Logs
</summary>

```shell
$ WECHATY_LOG=silly node ding-dong-bot.js
12:15:53 SILL Puppet Config: WECHATY_LOG set level to silly
12:15:53 INFO Config registering process.on("unhandledRejection") for development/debug
12:15:53 VERB Config constructor()
12:15:53 VERB Wechaty constructor()
12:15:53 VERB StateSwitch constructor(Wechaty, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
12:15:53 VERB StateSwitch constructor(WechatyReady, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
12:15:53 VERB Wechaty on(scan, listener) registered
12:15:53 VERB Wechaty on(login, listener) registered
12:15:53 VERB Wechaty on(logout, listener) registered
12:15:53 VERB Wechaty on(message, listener) registered
12:15:53 VERB Wechaty <wechaty-puppet-hostie>(ding-dong-bot) start() v0.41.17 is starting...
12:15:53 VERB Wechaty id: ckide..iy
12:15:53 SILL StateSwitch <Wechaty> on() is false
12:15:53 SILL StateSwitch <WechatyReady> off() is true
12:15:53 VERB StateSwitch <WechatyReady> off(true) <- (true)
12:15:53 SILL StateSwitch <Wechaty> on() is false
12:15:53 VERB StateSwitch <Wechaty> on(pending) <- (false)
12:15:53 VERB MemoryCard constructor("ding-dong-bot")
12:15:53 VERB MemoryCard getStorage() for storage type: N/A
12:15:53 VERB getStorage name: ding-dong-bot, options: {"type":"file"}
12:15:53 VERB StorageFile constructor(ding-dong-bot, ...)
12:15:53 VERB StorageBackend constructor(ding-dong-bot, { type: file })
12:15:53 VERB MemoryCard load() from storage: StorageFile</path/to/.../ding-dong-bot.memory-card.json>
12:15:53 VERB StorageFile load() from /path/to/.../ding-dong-bot.memory-card.json
12:15:53 VERB MemoryCard load() file not exist, NOOP
12:15:53 VERB Wechaty initPuppet() 
12:15:53 VERB MemoryCard multiplex(puppet)
12:15:53 VERB MemoryCard static multiplex(MemoryCard<ding-dong-bot>, puppet)
12:15:53 VERB MemoryCard constructor({"name":"ding-dong-bot","multiplex":{"name":"puppet","parent":{"options":{"name":"ding-dong-bot"},"name":"ding-dong-bot","payload":{},"multiplexNameList":[],"storage":{"name":"ding-dong-bot","options":{"type":"file"},"absFileName":"/path/to/.../ding-dong-bot.memory-card.json"}}}})
12:15:53 VERB PuppetManager resolve({puppet: wechaty-puppet-hostie, puppetOptions: undefined})
12:15:53 VERB PuppetManager resolveName(wechaty-puppet-hostie)
12:15:53 VERB PuppetManager checkModule(wechaty-puppet-hostie)
12:15:53 SILL PuppetManager checkModule() wechaty-puppet-hostie installed version 0.8.3 satisfied range ^0.8.3
12:15:53 VERB Puppet constructor({}) #0
12:15:53 VERB StateSwitch constructor(PuppetHostie, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
12:15:53 VERB MemoryCard constructor(undefined)
12:15:53 VERB MemoryCard getStorage() for storage type: N/A
12:15:53 VERB MemoryCard load() from storage: N/A
12:15:53 VERB MemoryCard load() no storage
12:15:53 VERB Puppet constructor() watchdog timeout set to 60 seconds
12:15:53 VERB HotImport callerResolve(., /../wechaty-getting-started/node_modules/wechaty-puppet/dist/src/puppet.js)
12:15:53 SILL HotImport callerResolve() callsites() file=/../wechaty-getting-started/node_modules/hot-import/dist/src/hot-import.js, type=Object
12:15:53 SILL HotImport callerResolve() callsites() file=/../wechaty-getting-started/node_modules/wechaty-puppet/dist/src/puppet.js, type=null
12:15:53 SILL HotImport callerResolve() callsites() file=/../wechaty-getting-started/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js, type=null
12:15:53 SILL HotImport callerResolve() callerFile=/../wechaty-getting-started/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js
12:15:53 VERB Puppet constructor() childClassPath=/../wechaty-getting-started/node_modules/wechaty-puppet-hostie/dist/src/client
12:15:53 VERB Puppet constructor() memory.load() done
12:15:53 VERB Puppet setMemory()
12:15:53 VERB Wechaty initPuppetEventBridge(Puppet#0<PuppetHostie>(ding-dong-bot))
12:15:53 VERB Wechaty initPuppetEventBridge() puppet.on(friendship) (listenerCount:0) registering...
12:15:53 VERB Wechaty initPuppetEventBridge() puppet.on(login) (listenerCount:0) registering...
12:15:53 VERB Wechaty initPuppetEventBridge() puppet.on(logout) (listenerCount:0) registering...
12:15:53 VERB Wechaty initPuppetEventBridge() puppet.on(message) (listenerCount:0) registering...
12:15:53 VERB Wechaty initPuppetEventBridge() puppet.on(room-invite) (listenerCount:0) registering...
12:15:53 VERB Wechaty initPuppetEventBridge() puppet.on(room-join) (listenerCount:0) registering...
12:15:53 VERB Wechaty initPuppetEventBridge() puppet.on(room-leave) (listenerCount:0) registering...
12:15:53 VERB Wechaty initPuppetEventBridge() puppet.on(room-topic) (listenerCount:0) registering...
12:15:53 VERB Wechaty initPuppetEventBridge() puppet.on(scan) (listenerCount:0) registering...
12:15:53 VERB Wechaty initPuppetEventBridge() puppet.on(dong) (listenerCount:0) registering...
12:15:53 VERB Wechaty initPuppetEventBridge() puppet.on(error) (listenerCount:0) registering...
12:15:53 VERB Wechaty initPuppetEventBridge() puppet.on(heartbeat) (listenerCount:1) registering...
12:15:53 VERB Wechaty initPuppetEventBridge() puppet.on(ready) (listenerCount:0) registering...
12:15:53 VERB Wechaty initPuppetEventBridge() puppet.on(reset) (listenerCount:1) registering...
12:15:53 VERB Wechaty initAccessory(Puppet#0<PuppetHostie>(ding-dong-bot))
12:15:53 SILL Accessory <Contact> static set wechaty = "Wechaty#ckide0bef0000rufuhrbi8uiy<>(ding-dong-bot)"
12:15:53 SILL Accessory <ContactSelf> static set wechaty = "Wechaty#ckide0bef0000rufuhrbi8uiy<>(ding-dong-bot)"
12:15:53 SILL Accessory <Friendship> static set wechaty = "Wechaty#ckide0bef0000rufuhrbi8uiy<>(ding-dong-bot)"
12:15:53 SILL Accessory <Image> static set wechaty = "Wechaty#ckide0bef0000rufuhrbi8uiy<>(ding-dong-bot)"
12:15:53 SILL Accessory <Message> static set wechaty = "Wechaty#ckide0bef0000rufuhrbi8uiy<>(ding-dong-bot)"
12:15:53 SILL Accessory <Room> static set wechaty = "Wechaty#ckide0bef0000rufuhrbi8uiy<>(ding-dong-bot)"
12:15:53 SILL Accessory <RoomInvitation> static set wechaty = "Wechaty#ckide0bef0000rufuhrbi8uiy<>(ding-dong-bot)"
12:15:53 SILL Accessory <Tag> static set wechaty = "Wechaty#ckide0bef0000rufuhrbi8uiy<>(ding-dong-bot)"
12:15:53 SILL Accessory <Contact> static set puppet = "Puppet#0<PuppetHostie>(ding-dong-bot)"
12:15:53 SILL Accessory <ContactSelf> static set puppet = "Puppet#0<PuppetHostie>(ding-dong-bot)"
12:15:53 SILL Accessory <Friendship> static set puppet = "Puppet#0<PuppetHostie>(ding-dong-bot)"
12:15:53 SILL Accessory <Image> static set puppet = "Puppet#0<PuppetHostie>(ding-dong-bot)"
12:15:53 SILL Accessory <Message> static set puppet = "Puppet#0<PuppetHostie>(ding-dong-bot)"
12:15:53 SILL Accessory <Room> static set puppet = "Puppet#0<PuppetHostie>(ding-dong-bot)"
12:15:53 SILL Accessory <RoomInvitation> static set puppet = "Puppet#0<PuppetHostie>(ding-dong-bot)"
12:15:53 SILL Accessory <Tag> static set puppet = "Puppet#0<PuppetHostie>(ding-dong-bot)"
12:15:53 VERB PuppetHostie start()
12:15:53 SILL StateSwitch <PuppetHostie> on() is false
12:15:53 SILL StateSwitch <PuppetHostie> on() is false
12:15:53 VERB StateSwitch <PuppetHostie> on(pending) <- (false)
12:15:53 VERB PuppetHostie startGrpcClient()
12:15:53 VERB PuppetHostie startGrpcStream()
12:15:53 ERR PuppetHostie start() rejection: 14 UNAVAILABLE: DNS resolution failed
12:15:53 SILL StateSwitch <PuppetHostie> off() is false
12:15:53 VERB StateSwitch <PuppetHostie> off(true) <- (false)
{ Error: 14 UNAVAILABLE: DNS resolution failed
    at Object.exports.createStatusError (/../wechaty-getting-started/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/../wechaty-getting-started/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/../wechaty-getting-started/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/../wechaty-getting-started/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/../wechaty-getting-started/node_modules/grpc/src/client_interceptors.js:847:24)
  code: 14,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'DNS resolution failed' }
12:15:53 ERR Wechaty start() exception: 14 UNAVAILABLE: DNS resolution failed
12:15:53 ERR StarterBot Error: 14 UNAVAILABLE: DNS resolution failed
12:15:53 VERB PuppetHostie startGrpcStream() eventStream.on(error) Error: 14 UNAVAILABLE: DNS resolution failed
12:15:53 SILL Puppet constructor() this.on(reset) payload: "{"data":"startGrpcStream() eventStream.on(error) Error: 14 UNAVAILABLE: DNS resolution failed"}"
12:15:53 SILL Puppet constructor() resetThrottleQueue.subscribe() reason: "startGrpcStream() eventStream.on(error) Error: 14 UNAVAILABLE: DNS resolution failed"
12:15:53 VERB Puppet reset(startGrpcStream() eventStream.on(error) Error: 14 UNAVAILABLE: DNS resolution failed)
12:15:53 VERB PuppetHostie stop()
```

</details>

## 7. Additional context
No any other context about the problem here.

[bug]

**Comment by suntong** [comment]
Took a look at the `grpc/src/client_interceptors.js` around `onReceiveStatus`'s callback:

```js
InterceptingListener.prototype.onReceiveStatus = function(status) {
  this._callNext('onReceiveStatus', [status]);
};

. . .

        response.metadata =
          Metadata._fromCoreRepresentation(response.metadata);
        first_listener.onReceiveMetadata(response.metadata);
        first_listener.onReceiveMessage(deserialized);
        first_listener.onReceiveStatus(status);
```

and have no idea where the problem is.

**Comment by suntong** [comment]
More details, I've been using 

`export WECHATY_PUPPET_HOSTIE_ENDPOINT=114.215.83.32:7777`

as instructed, but am getting:

```json
{ Error: 16 UNAUTHENTICATED: {code:8,message:"A token(114.215.83.32:7777) must be prefixed with a 'puppet_rock_' "}
```

So I changed it to 

`export WECHATY_PUPPET_HOSTIE_ENDPOINT=puppet_rock_114.215.83.32:7777
`

I.e., I'm suspecting that the `DNS resolution failed` might have something to do with `HOSTIE_ENDPOINT=puppet_rock_114.215.83.32:7777`

**Comment by jcai** [comment]
The latest version doesn't need `WECHATY_PUPPET_HOSTIE_ENDPOINT` variable.From the log,I think you may set  your token incorrectly.

**Comment by suntong** [comment]
> The latest version doesn't need WECHATY_PUPPET_HOSTIE_ENDPOINT variable.

which version it is? Mine is `wechaty-puppet-hostie@0.11.10` and `npm outdated` is not listing wechaty-puppet-hostie, yet, this is what I'm getting if not setting WECHATY_PUPPET_HOSTIE_ENDPOINT variable:

```
$ node ding-dong-bot.js
14:03:27 ERR PuppetHostie start() rejection: no endpoint
Error: no endpoint
    at PuppetHostie.<anonymous> (/.../node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:69:31)
```

**Comment by suntong** [comment]
OK. I redid the installation from scratch.

```sh
rm -rf package*.json node_modules/
npm init -y
npm install wechaty@next
```

and now I have a super clean `package.json` file:

```
$ jq .dependencies package.json
{
  "wechaty": "^0.51.8"
}
```
and concise installed packages:

```
└─┬ wechaty@0.51.8
  ├─┬ wechaty-puppet@0.33.6
  │ ├─┬ file-box@0.16.4
  ├─┬ wechaty-puppet-hostie@0.11.10
```

Indeed `WECHATY_PUPPET_HOSTIE_ENDPOINT` is no longer necessary, but I'm still getting the above reported error:

```
unset WECHATY_PUPPET_HOSTIE_ENDPOINT

$ node ding-dong-bot.js
23:24:46 ERR PuppetHostie start() rejection: 16 UNAUTHENTICATED: {code:8,message:"A token(114.215.83.32:7777) must be prefixed with a 'puppet_rock_' "}
{ Error: 16 UNAUTHENTICATED: {code:8,message:"A token(114.215.83.32:7777) must be prefixed with a 'puppet_rock_' "}
    at Object.exports.createStatusError (/.../node_modules/grpc/src/common.js:91:15)
. . .
```

**Comment by huan** [comment]
> { Error: 16 UNAUTHENTICATED: {code:8,message:"A token(114.215.83.32:7777) must be prefixed with a 'puppet_rock_' "}

The above log message is telling you that your token format is not right.

You need to add the prefix `puppet_rock_` to your token and try again.

**Comment by suntong** [comment]
> The above log message is telling you that your token format is not right.

Note that it complains about the token `114.215.83.32:7777`, which is the IP of the `WECHATY_PUPPET_HOSTIE_ENDPOINT`, which is I don't need to set any more.

> You need to add the prefix `puppet_rock_` to your token and try again.

I've tried both, with and without prefix `puppet_rock_` to my token, and the result is exactly the same, which makes me believe that it is the `WECHATY_PUPPET_HOSTIE_ENDPOINT`'s internal problem. 

@huan / @jcai, if it is working in your environment, please at least let me know what versions of your packages, and what exactly environment variables I need to set. Thx.

**Comment by huan** [comment]
@suntong can you get the IP and port information from the https://api.chatie.io/v0/hosties/YOUR_TOKEN ?

**Comment by huan** [comment]
And I agree that the below error message is confusing:

> A token(114.215.83.32:7777) must be prefixed with a 'puppet_rock_' 
 
Ip should not be prefixed, I guess it should be the token that user provided? @jcai

**Comment by suntong** [comment]
![image](https://user-images.githubusercontent.com/422244/101718504-54000380-3a6f-11eb-9a80-b11b42397f3b.png)

**Comment by huan** [comment]
That's wired. If the token can be resolved right, it should be able to work.

Maybe you have to contact @jcai for diving deeper.

Our Friday.BOT is running with a rock token recently, it works without any problem now.
