### ISSUE TITLE
[BUG]WorkPro: 持续性GRPC心跳超时

### ISSUE THREAD

**Issue by xsun2001** [wechaty/puppet-service-providers#382]
**Describe the bug**

登陆一分钟后会准时超时：

```
06:08:41 WARN PuppetWatchdogAgent start() reset() reason: {"data":"onGrpcStreamEvent(EVENT_TYPE_DONG)","timeoutMilliseconds":60000}
```

或

```
06:56:07 WARN PuppetWatchdogAgent start() reset() reason: {"data":"regular heartbeat","timeoutMilliseconds":60000}
```

我加入了简单的重连逻辑：

```typescript
bot.on("error", async () => {
            log.warn("WechatProxy", "Restarting")
            await bot?.reset();
        });
```

但是超时问题仍然存在，导致服务非常不稳定。

已经在环境变量中正确配置了服务发现和禁用tls：

```
WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com
WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true
```

**Info**

 - Platform[e.g. Windows/Mac/Linux]: Mac/Linux/Docker Image
 - Runtime version[e.g. node/JAVA]:  Node v21
 - Wechaty version: 
 ```
	"@grpc/grpc-js": "1.9.13",  // Pin the grpc-js version to avoid port issue
    "@juzi/wechaty": "1.0.96",
    "@juzi/wechaty-puppet": "1.0.86",
    "@juzi/wechaty-puppet-service": "1.0.93",
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xsun2001** [comment]
另外我们还观测到会出现类似内存泄漏的状况，希望您可以注意一下相关的问题：

<img width="747" alt="截屏2024-03-07 15 41 12" src="https://github.com/wechaty/puppet-supports/assets/14010993/25077ed2-d253-4eed-a0a2-539ba5f5baf2">

**Comment by su-chang** [comment]
上述问题有最简复现代码么？可以提供下，有助于定位问题。

**Comment by xsun2001** [comment]
如果您是指掉线问题，那么我们的机器人没有复杂的逻辑，只是把消息转发给我们的后端。

如果您指的是意外的内存占用，我们确实没办法定位具体的问题点。

**Comment by xsun2001** [comment]
下面是一个会掉线的最简单的echo bot：

`index.ts`
```typescript
import "dotenv/config";
import {Message, Wechaty, WechatyBuilder} from "@juzi/wechaty";
import {PuppetService} from "@juzi/wechaty-puppet-service";

let bot: Wechaty = WechatyBuilder.build({
    puppet: new PuppetService()
});

bot.on("message", async (msg: Message) => {
    await msg.say(msg.text());
});

bot.start().then(() => console.log("Started"))
```

`package.json`
```json
{
  "name": "wechaty-mini",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.ts",
  "scripts": {
    "start": "npx ts-node src/index.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/express": "^4.17.21",
    "@types/node": "^20.11.25",
    "typescript": "^5.4.2"
  },
  "dependencies": {
    "@grpc/grpc-js": "1.9.13",
    "@juzi/wechaty": "1.0.96",
    "@juzi/wechaty-puppet": "1.0.86",
    "@juzi/wechaty-puppet-service": "1.0.93",
    "dotenv": "^16.4.5"
  }
}
```

日志：
```
18:19:06 INFO PuppetSkeleton start()
18:19:06 INFO PuppetService start() instanciating GrpcManager ...
18:19:06 INFO PuppetService start() instanciating GrpcManager ... done
18:19:06 INFO PuppetService start() setting up bridge grpc event stream ...
18:19:06 INFO PuppetService start() setting up bridge grpc event stream ... done
18:19:06 INFO PuppetService start() starting grpc manager...
18:19:06 WARN last event was 95950.737 seconds ago, will not request event cache 
18:19:06 WARN GrpcManager initClient() TLS: disabled (INSECURE)
18:19:06 INFO GrpcManager startStream() connecting event stream with account 16888*******432 and seq undefined
18:19:07 INFO PuppetService received grpc event EVENT_TYPE_LOGIN on Thu Mar 07 2024 18:19:07 GMT+0800 (China Standard Time), content: "{\"contactId\":\"16888*******432\"}", seq: 0, timestamp: 1709806747173
18:19:07 WARN last event was 95951.226 seconds ago, will not request event cache 
18:19:07 INFO PuppetLoginMixin login(16888*******432)
18:19:07 INFO PuppetService start() starting grpc manager... done
18:19:07 INFO PuppetService start healthCheck
18:19:07 INFO PuppetService onStart() ... done
Started
18:19:16 INFO PuppetService received grpc event EVENT_TYPE_MESSAGE on Thu Mar 07 2024 18:19:16 GMT+0800 (China Standard Time), content: "{\"messageId\":\"8edca42dc3a8204e64b42866a3f845e0\"}", seq: 1930, timestamp: 1709806756587
18:19:16 WARN last event was 95960.644 seconds ago, will not request event cache 
18:19:16 INFO PuppetService messageSend(7881301793077974, hrllo) about to call grpc
18:19:17 INFO PuppetService messageSend(7881301793077974, hrllo) grpc called, messageId: 0c84672e7e060c28f7a1f823a11774d1
18:19:22 INFO PuppetService received grpc event EVENT_TYPE_READY on Thu Mar 07 2024 18:19:22 GMT+0800 (China Standard Time), content: "{\"data\":\"data ready\"}", seq: 0, timestamp: 1709806762168
18:20:28 WARN PuppetWatchdogAgent start() reset() reason: {"data":"onGrpcStreamEvent(EVENT_TYPE_DONG)","timeoutMilliseconds":60000}
/Users/xsun2001/Documents/Projects/2023-summer/miracleplus/untitled1/node_modules/.pnpm/@juzi+wechaty-puppet@1.0.86_rxjs@7.8.1/node_modules/@juzi/wechaty-puppet/src/agents/watchdog-agent.ts:65
      this.puppet.emit('error', new Error(
                                ^
GError: WatchdogAgent reset: lastFood: "{"data":"onGrpcStreamEvent(EVENT_TYPE_DONG)","timeoutMilliseconds":60000}"
    at Watchdog.reset (/Users/xsun2001/Documents/Projects/2023-summer/miracleplus/untitled1/node_modules/.pnpm/@juzi+wechaty-puppet@1.0.86_rxjs@7.8.1/node_modules/@juzi/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:514:28)
    at Watchdog.emit (node:domain:488:12)
    at Timeout._onTimeout (/Users/xsun2001/Documents/Projects/2023-summer/miracleplus/untitled1/node_modules/.pnpm/watchdog@0.9.2/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"onGrpcStreamEvent(EVENT_TYPE_DONG)","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (/Users/xsun2001/Documents/Projects/2023-summer/miracleplus/untitled1/node_modules/.pnpm/@juzi+wechaty-puppet@1.0.86_rxjs@7.8.1/node_modules/@juzi/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:514:28)\n' +
    '    at Watchdog.emit (node:domain:488:12)\n' +
    '    at Timeout._onTimeout (/Users/xsun2001/Documents/Projects/2023-summer/miracleplus/untitled1/node_modules/.pnpm/watchdog@0.9.2/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:573:17)\n' +
    '    at processTimers (node:internal/timers:514:7)'
}
```

**Comment by xsun2001** [comment]
另外我也试过对grpc打补丁的方法以代替固定grpc版本：https://github.com/wechaty/puppet-supports/issues/364#issuecomment-1952270004 。但是效果都是一样的。

**Comment by su-chang** [comment]
你这个token是不是存在多个程序中在使用？

**Comment by su-chang** [comment]
从 2024-03-05 @ 11:20:49 开始，这个token应该是在多地使用了，从而导致你遇到的这个问题。检查下云服务或本地终端啥的是否在同时使用。

**Comment by xsun2001** [comment]
经过我们的检查确实存在这一情况，关闭多余服务后已经恢复正常，非常感谢！
