### ISSUE TITLE
WXWork: 下载图片异常，请问是什么原因

### ISSUE THREAD

**Issue by chenag** [wechaty/puppet-service-providers#422]
## Question
13 INTERNAL: exec task timeout, uniqueQueueId: server-server-regular-download-uniqueue-parallel-0
{"code":13,"details":"exec task timeout, uniqueQueueId: server-server-regular-download-uniqueue-parallel-0","metadata":{"content-type":["application/grpc+proto"],"date":["Fri, 12 Apr 2024 09:07:14 GMT"],"authorization":["Wechaty undefined"]},"stack":"Error: 13 INTERNAL: exec task timeout, uniqueQueueId: server-server-regular-download-uniqueue-parallel-0\n    at callErrorFromStatus (D:\\soft\\qwrobot\\qwrobot\\node_modules\\@grpc\\grpc-js\\build\\src\\call.js:31:19)\n    at Object.onReceiveStatus (D:\\soft\\qwrobot\\qwrobot\\node_modules\\@grpc\\grpc-js\\build\\src\\client.js:192:76)\n    at Object.onReceiveStatus (D:\\soft\\qwrobot\\qwrobot\\node_modules\\@grpc\\grpc-js\\build\\src\\client-interceptors.js:360:141)\n    at Object.onReceiveStatus (D:\\soft\\qwrobot\\qwrobot\\node_modules\\@grpc\\grpc-js\\build\\src\\client-interceptors.js:323:181)\n    at D:\\soft\\qwrobot\\qwrobot\\node_modules\\@grpc\\grpc-js\\build\\src\\resolving-call.js:99:78\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)\nfor call at\n    at ServiceClientImpl.makeUnaryRequest (D:\\soft\\qwrobot\\qwrobot\\node_modules\\@grpc\\grpc-js\\build\\src\\client.js:160:32)\n    at ServiceClientImpl.messageFile (D:\\soft\\qwrobot\\qwrobot\\node_modules\\@grpc\\grpc-js\\build\\src\\make-client.js:105:19)\n    at node:internal/util:442:7\n    at new Promise (<anonymous>)\n    at bound  (node:internal/util:428:12)\n    at PuppetService.messageFile (file:///D:/soft/qwrobot/qwrobot/node_modules/@juzi/wechaty-puppet-service/dist/esm/src/client/puppet-service.js:874:44)\n    at WechatifiedUserClass.toFileBox (file:///D:/soft/qwrobot/qwrobot/node_modules/@juzi/wechaty/dist/esm/src/user-modules/message.js:995:51)\n    at WechatyImpl.onMessage (file:///D:/soft/qwrobot/qwrobot/src/wechatyBot.ts:183:48)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}

**Comment by su-chang** [comment]
请求超时了，可以重试下看看，下载富媒体消息，最好自行做个队列下载。
