### ISSUE TITLE
[BUG]WorkPro: 发送图片报错Unknown send message failed! cgi error code: (-4048) message:

### ISSUE THREAD

**Issue by leochen-g** [wechaty/puppet-service-providers#469]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

发送图片的时候经常会报错，确定登录状态没问题，文字消息也是可以发出去的，但是就是图片无法发送

```
2024-05-31 17:24 +08:00: 群回复错误 Error: 13 INTERNAL: WorkproErrorCode: 23060, processSendMsgRsp(10926536758569282) contentType: Unknown send message failed! cgi error code: (-4048) message: .
2024-05-31 17:24 +08:00: at callErrorFromStatus (/app/client-server/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
2024-05-31 17:24 +08:00: at Object.onReceiveStatus (/app/client-server/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
2024-05-31 17:24 +08:00: at Object.onReceiveStatus (/app/client-server/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
2024-05-31 17:24 +08:00: at Object.onReceiveStatus (/app/client-server/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
2024-05-31 17:24 +08:00: at /app/client-server/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
2024-05-31 17:24 +08:00: at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
2024-05-31 17:24 +08:00: for call at
2024-05-31 17:24 +08:00: at ServiceClientImpl.makeUnaryRequest (/app/client-server/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
2024-05-31 17:24 +08:00: at ServiceClientImpl.messageSendFile (/app/client-server/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
2024-05-31 17:24 +08:00: at node:internal/util:442:7
2024-05-31 17:24 +08:00: at new Promise (<anonymous>)
2024-05-31 17:24 +08:00: at bound (node:internal/util:428:12)
2024-05-31 17:24 +08:00: at PuppetService.messageSendFile (file:///xxx/client-server/node_modules/@juzi/wechaty-puppet-service/dist/esm/src/client/puppet-service.js:1052:44)
2024-05-31 17:24 +08:00: at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-05-31 17:24 +08:00: at async file:///xxx/client-server/node_modules/@juzi/wechaty/dist/esm/src/sayable/deliver-sayable.js:25:17
2024-05-31 17:24 +08:00: at async WechatifiedUserClass.say (file:///app/client-server/node_modules/@juzi/wechaty/dist/esm/src/user-modules/room.js:457:21)
2024-05-31 17:24 +08:00: at async WechatyImpl.roomSay (file:///xxx/client-server/client/src/utils/index.js:166:13) {
2024-05-31 17:24 +08:00: code: 13,
2024-05-31 17:24 +08:00: details: 'WorkproErrorCode: 23060, processSendMsgRsp(10926536758569282) contentType: Unknown send message failed! cgi error code: (-4048) message: .',
2024-05-31 17:24 +08:00: metadata: Metadata {
2024-05-31 17:24 +08:00: internalRepr: Map(3) {
2024-05-31 17:24 +08:00: 'content-type' => [Array],
2024-05-31 17:24 +08:00: 'date' => [Array],
2024-05-31 17:24 +08:00: 'authorization' => [Array]
2024-05-31 17:24 +08:00: },
2024-05-31 17:24 +08:00: options: {}
2024-05-31 17:24 +08:00: }
2024-05-31 17:24 +08:00: }
```

**Info**

 - Platform[e.g. Windows/Mac/Linux]: Linux
 - Runtime version[e.g. node/JAVA]:Node
 - Wechaty version:  "@juzi/wechaty": "^1.0.96",
 - Wechaty Puppet version:  "@juzi/wechaty-puppet-service": "^1.0.93", "@juzi/wechaty-puppet": "^1.0.86",

**To Reproduce**

```
            url = "https://sjxjjs.examp/api.jpg"
            let obj = FileBox.fromUrl(encodeURI(msg.url))
            await obj.ready()
            await contact.say(obj)
```

**Expected behavior**

出现了上述报错，属于偶发性的，有的可以发送成功

**Screenshots**

<img width="1203" alt="image" src="https://github.com/wechaty/puppet-supports/assets/20028566/b5ad960c-3623-4217-b1ab-bb33ccff29db">

**Additional context**

**Comment by hcfw007** [comment]
-4048 代表发送被限制

**Comment by leochen-g** [comment]
> -4048 代表发送被限制

好的 谢谢
