### ISSUE TITLE
[BUG]WorkPro:启动报错

### ISSUE THREAD

**Issue by wcljava2018** [wechaty/puppet-service-providers#470]
WARN GrpcManager initClient() TLS: disabled (INSECURE)
D:\code\workpro-getting-started-main\node_modules\@grpc\grpc-js\src\subchannel-address.ts:40
  return 'port' in address;
               ^
TypeError: Cannot use 'in' operator to search for 'port' in undefined
    at isTcpSubchannelAddress (D:\code\workpro-getting-started-main\node_modules\@grpc\grpc-js\src\subchannel-address.ts:40:16)
    at interleaveAddressFamilies (D:\code\workpro-getting-started-main\node_modules\@grpc\grpc-js\src\load-balancer-pick-first.ts:145:27)
    at PickFirstLoadBalancer.updateAddressList (D:\code\workpro-getting-started-main\node_modules\@grpc\grpc-js\src\load-balancer-pick-first.ts:533:25)
    at ChildLoadBalancerHandler.updateAddressList (D:\code\workpro-getting-started-main\node_modules\@grpc\grpc-js\src\load-balancer-child-handler.ts:137:19)        
    at onSuccessfulResolution (D:\code\workpro-getting-started-main\node_modules\@grpc\grpc-js\src\resolving-load-balancer.ts:302:34)
    at processTicksAndRejections (node:internal/process/task_queues:86:22)

**Comment by su-chang** [comment]
参考这个：https://github.com/wechaty/puppet-supports/issues/438#issuecomment-2111510238

**Comment by AIAmber** [comment]
这个问题有后续吗?
