### ISSUE TITLE
[BUG]WorkPro: 拉机器人时候转换错误

### ISSUE THREAD

**Issue by doupingtest** [wechaty/puppet-service-providers#491]
content: "{\"inviteeIdList\":[\"7881300321952648\"],\"inviterId\":\"1688857524377660\",\"roomId\":\"R:10869385883898992\",\"timestamp\":1718350079}", seq: 19791, timestamp: 1718350082104

GError: 13 INTERNAL: Cannot convert 108693858838989927881300321952648 to a BigInt

**Comment by su-chang** [comment]
是否可以稳定复现？最好能提供完整的错误日志

**Comment by doupingtest** [comment]
可以稳定复现的, 只要拉机器人进群必定爆转换id错误

**Comment by doupingtest** [comment]
17:19:43 INFO PuppetService received grpc event EVENT_TYPE_ROOM_LEAVE on Sat Jun 15 2024 17:19:43 GMT+0800 (China Standard Time), content: "{\"removeeIdList\":[\"1688856087549940\"],\"removerId\":\"1688856087549940\",\"roomId\":\"R:207625821031686\",\"timestamp\":1718443181000}", seq: 23323, timestamp: 1718443183205
GError: 13 INTERNAL: Cannot convert 2076258210316861688854453497605 to a BigInt
    at callErrorFromStatus (/usr/local/deploy/yisizhiyu-ms-front/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/usr/local/deploy/yisizhiyu-ms-front/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/usr/local/deploy/yisizhiyu-ms-front/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/usr/local/deploy/yisizhiyu-ms-front/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /usr/local/deploy/yisizhiyu-ms-front/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/usr/local/deploy/yisizhiyu-ms-front/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
    at ServiceClientImpl.roomPayload (/usr/local/deploy/yisizhiyu-ms-front/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at node:internal/util:364:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:350:12)
    at PuppetService.roomRawPayload (file:///usr/local/deploy/yisizhiyu-ms-front/node_modules/@juzi/wechaty-puppet-service/dist/esm/src/client/puppet-service.js:1199:44)
    at async PuppetService.roomPayload (file:///usr/local/deploy/yisizhiyu-ms-front/node_modules/@juzi/wechaty-puppet/dist/esm/src/mixins/room-mixin.js:146:32)
    at async WechatifiedUserClass.ready (file:///usr/local/deploy/yisizhiyu-ms-front/node_modules/@juzi/wechaty/dist/esm/src/user-modules/room.js:297:24)
    at async Function.find (file:///usr/local/deploy/yisizhiyu-ms-front/node_modules/@juzi/wechaty/dist/esm/src/user-modules/room.js:162:17)
    at async PuppetService.<anonymous> (file:///usr/local/deploy/yisizhiyu-ms-front/node_modules/@juzi/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:567:54) {
  code: 13,
  details: 'Cannot convert 207625821031686\x1F1688854453497605 to a BigInt'
}

**Comment by doupingtest** [comment]
17:19:43 INFO PuppetService received grpc event EVENT_TYPE_ROOM_LEAVE on Sat Jun 15 2024 17:19:43 GMT+0800 (China Standard Time), content: "{\"removeeIdList\":[\"1688856087549940\"],\"removerId\":\"1688856087549940\",\"roomId\":\"R:207625821031686\",\"timestamp\":1718443181000}", seq: 23323, timestamp: 1718443183205
GError: 13 INTERNAL: Cannot convert 2076258210316861688854453497605 to a BigInt
    at callErrorFromStatus (/usr/local/deploy/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/usr/local/deploy/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/usr/local/deploy/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/usr/local/deploy/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /usr/local/deploy/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/usr/local/deploy/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
    at ServiceClientImpl.roomPayload (/usr/local/deploy/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at node:internal/util:364:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:350:12)
    at PuppetService.roomRawPayload (file:///usr/local/deploy/node_modules/@juzi/wechaty-puppet-service/dist/esm/src/client/puppet-service.js:1199:44)
    at async PuppetService.roomPayload (file:///usr/local/deploy/node_modules/@juzi/wechaty-puppet/dist/esm/src/mixins/room-mixin.js:146:32)
    at async WechatifiedUserClass.ready (file:///usr/local/deploy/node_modules/@juzi/wechaty/dist/esm/src/user-modules/room.js:297:24)
    at async Function.find (file:///usr/local/deploy/node_modules/@juzi/wechaty/dist/esm/src/user-modules/room.js:162:17)
    at async PuppetService.<anonymous> (file:///usr/local/deploy/node_modules/@juzi/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:567:54) {
  code: 13,
  details: 'Cannot convert 207625821031686\x1F1688854453497605 to a BigInt'
}

**Comment by su-chang** [comment]
看起来是群数据转换的时候使用的id不对，是否在程序内部用错了id呢？主要是这个数据不对，207625821031686�1688854453497605

同时也可以提供下使用的wechaty的版本信息。

**Comment by doupingtest** [comment]
"@juzi/wechaty": "1.0.97",
    "@juzi/wechaty-puppet": "1.0.87",
    "@juzi/wechaty-puppet-service": "1.0.94",

**Comment by doupingtest** [comment]
默认的id 没做过任何操作
邀请机器人 和 删除机器人报错 EVENT_TYPE_ROOM_LEAVE 还有一个EVENT_TYPE_ROOM_JOIN

**Comment by doupingtest** [comment]
11:03:17 INFO PuppetService received grpc event EVENT_TYPE_ROOM_JOIN on Mon Jun 17 2024 11:03:17 GMT+0800 (China Standard Time), content: "{\"inviteeIdList\":[\"1688857681552706\"],\"inviterId\":\"1688850509964823\",\"roomId\":\"R:215924753292443\",\"timestamp\":1718593396}", seq: 26560, timestamp: 1718593397470
GError: 13 INTERNAL: Cannot convert 2159247532924431688857681552706 to a BigInt
    at callErrorFromStatus (/usr/local/deploy/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/usr/local/deploy/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/usr/local/deploy/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/usr/local/deploy/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /usr/local/deploy/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/usr/local/deploy/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
    at ServiceClientImpl.roomPayload (/usr/local/deploy/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at node:internal/util:364:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:350:12)
    at PuppetService.roomRawPayload (file:///usr/local/deploy/node_modules/@juzi/wechaty-puppet-service/dist/esm/src/client/puppet-service.js:1199:44)
    at async PuppetService.roomPayload (file:///usr/local/deploy/node_modules/@juzi/wechaty-puppet/dist/esm/src/mixins/room-mixin.js:146:32)
    at async WechatifiedUserClass.ready (file:///usr/local/deploy/node_modules/@juzi/wechaty/dist/esm/src/user-modules/room.js:297:24)
    at async Function.find (file:///usr/local/deploy/node_modules/@juzi/wechaty/dist/esm/src/user-modules/room.js:162:17)
    at async PuppetService.<anonymous> (file:///usr/local/deploy/node_modules/@juzi/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:567:54) {
  code: 13,
  details: 'Cannot convert 215924753292443\x1F1688857681552706 to a BigInt'
}

**Comment by hcfw007** [comment]
这个你只要用 bot.on('error') 监听事件然后忽略即可。

**Comment by doupingtest** [comment]
ok
