### ISSUE TITLE
[BUG]WorkPro: 启动机器人报错

### ISSUE THREAD

**Issue by zhongyufan** [wechaty/puppet-service-providers#500]
启动机器人报错，错误如下

/Users/zhong/Desktop/code/qiaoying-server/node_modules/.pnpm/@juzi+wechaty-puppet-service@1.0.97_@juzi+wechaty-puppet@1.0.86_brolog@1.14.2_redux@4.2.1/node_modules/@juzi/wechaty-puppet-service/src/client/puppet-service.ts:244
    const seq     = event.getSeq()
                          ^
TypeError: event.getSeq is not a function
    at PuppetService.onGrpcStreamEvent (/Users/zhong/Desktop/code/qiaoying-server/node_modules/.pnpm/@juzi+wechaty-puppet-service@1.0.97_@juzi+wechaty-puppet@1.0.86_brolog@1.14.2_redux@4.2.1/node_modules/@juzi/wechaty-puppet-service/src/client/puppet-service.ts:244:27)
    at GrpcManager.emit (node:events:520:28)
    at GrpcManager.emit (node:domain:488:12)
    at GrpcManager.startStream (/Users/zhong/Desktop/code/qiaoying-server/node_modules/.pnpm/@juzi+wechaty-puppet-service@1.0.97_@juzi+wechaty-puppet@1.0.86_brolog@1.14.2_redux@4.2.1/node_modules/@juzi/wechaty-puppet-service/src/client/grpc-manager.ts:409:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at GrpcManager.start (/Users/zhong/Desktop/code/qiaoying-server/node_modules/.pnpm/@juzi+wechaty-puppet-service@1.0.97_@juzi+wechaty-puppet@1.0.86_brolog@1.14.2_redux@4.2.1/node_modules/@juzi/wechaty-puppet-service/src/client/grpc-manager.ts:161:5)
    at PuppetService.onStart (/Users/zhong/Desktop/code/qiaoying-server/node_modules/.pnpm/@juzi+wechaty-puppet-service@1.0.97_@juzi+wechaty-puppet@1.0.86_brolog@1.14.2_redux@4.2.1/node_modules/@juzi/wechaty-puppet-service/src/client/puppet-service.ts:163:5)
    at PuppetService.start (/Users/zhong/Desktop/code/qiaoying-server/node_modules/.pnpm/state-switch@1.7.1_brolog@1.14.2_gerror@1.0.16_rxjs@7.2.0/node_modules/state-switch/src/service-ctl/service-ctl.ts:89:9)
    at PuppetService.start (/Users/zhong/Desktop/code/qiaoying-server/node_modules/.pnpm/@juzi+wechaty-puppet@1.0.86_rxjs@7.2.0/node_modules/@juzi/wechaty-puppet/src/mixins/service-mixin.ts:34:7)
    at PuppetService.start (/Users/zhong/Desktop/code/qiaoying-server/node_modules/.pnpm/@juzi+wechaty-puppet@1.0.86_rxjs@7.2.0/node_modules/@juzi/wechaty-puppet/src/mixins/ready-mixin.ts:24:7)
    
    
    
        "@juzi/wechaty": "1.0.99",
        "wechaty": "^1.20.2",
    "wechaty-puppet-wechat": "^1.18.4",
    
    
   因为要用到个微的服务， 所以同时装了wechaty
   
   装了之后报错

**Comment by zhongyufan** [comment]
删除wechaty即可正常运行
