### ISSUE TITLE
WXWork: 机器人不定时报超时问题，紧急帮忙处理下

### ISSUE THREAD

**Issue by zhl0101** [wechaty/puppet-service-providers#521]
Please make sure you have read the [Wechaty Puppet Service: WXWork](https://wechaty.js.org/docs/puppet-services/wxwork) from Wechaty Official Website before you continue writting this issue.

## Question
GError: 1 CANCELLED: Call cancelled
    at callErrorFromStatus (/home/zycfc/dist/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/home/zycfc/dist/node_modules/@grpc/grpc-js/build/src/client.js:351:73)
    at Object.onReceiveStatus (/home/zycfc/dist/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /home/zycfc/dist/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeServerStreamRequest (/home/zycfc/dist/node_modules/@grpc/grpc-js/build/src/client.js:334:34)
    at ServiceClientImpl.event (/home/zycfc/dist/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at GrpcManager.startStream (file:///home/zycfc/dist/node_modules/wechaty-puppet-service/dist/esm/src/client/grpc-manager.js:232:41)
    at GrpcManager.start (file:///home/zycfc/dist/node_modules/wechaty-puppet-service/dist/esm/src/client/grpc-manager.js:121:20)
    at async PuppetService.onStart (file:///home/zycfc/dist/node_modules/wechaty-puppet-service/dist/esm/src/client/puppet-service.js:110:9)
    at async PuppetService.start (file:///home/zycfc/dist/node_modules/state-switch/dist/esm/src/service-ctl/service-ctl.js:62:17)
    at async PuppetService.start (file:///home/zycfc/dist/node_modules/wechaty-puppet/dist/esm/src/mixins/service-mixin.js:18:13)
    at async PuppetService.start (file:///home/zycfc/dist/node_modules/wechaty-puppet/dist/esm/src/mixins/ready-mixin.js:13:13)
    at async WechatyImpl.start (file:///home/zycfc/dist/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:48:21)
    at async WechatyImpl.start (file:///home/zycfc/dist/node_modules/state-switch/dist/esm/src/service-ctl/service-ctl.js:55:21) {
  code: 1,
  details: 'Call cancelled'
}
09:41:18 WARN PuppetWatchdogAgent start() reset() reason: {"data":"regular heartbeat","timeoutMilliseconds":60000}
GError: WatchdogAgent reset: lastFood: "{"data":"regular heartbeat","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///home/zycfc/dist/node_modules/wechaty-puppet/dist/esm/src/agents/watchdog-agent.js:45:39)
    at Watchdog.emit (node:events:390:28)
    at Timeout._onTimeout (file:///home/zycfc/dist/node_modules/watchdog/dist/esm/src/watchdog.js:81:18)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 2,

**Comment by su-chang** [comment]
尝试重连即可恢复
