### ISSUE TITLE
Other: 使用试用token出现 TypeError: Cannot use 'in' operator to search for 'port' in undefined 异常

### ISSUE THREAD

**Issue by xiaoEight** [wechaty/puppet-service-providers#528]
使用试用token 与 puppet: 'wechaty-puppet-service'，启动出现异常，导致无法使用,

已经http访问检查 token对应 https://[token-service-discovery-test.juzibot.com/v0/hosties/puppet_workpro_xxxxxx 包含返回值
如下：
{
    "host": "xx.xx.xx.191",
    "ip": "xx.xx.xx.191",
    "port": 4002
}

启动异常如下：
12:17:30 ERR Config ###########################
12:17:30 ERR Config Wechaty uncaughtException: TypeError: Cannot use 'in' operator to search for 'port' in undefined
    at isTcpSubchannelAddress (D:\Work\Development\NodeJS\wechaty-getting-started\node_modules\@grpc\grpc-js\build\src\subchannel-address.js:22:19)
    at subchannelAddressToString (D:\Work\Development\NodeJS\wechaty-getting-started\node_modules\@grpc\grpc-js\build\src\subchannel-address.js:43:9)
    at D:\Work\Development\NodeJS\wechaty-getting-started\node_modules\@grpc\grpc-js\build\src\load-balancer-pick-first.js:421:120
    at Array.map (<anonymous>)
    at PickFirstLoadBalancer.updateAddressList (D:\Work\Development\NodeJS\wechaty-getting-started\node_modules\@grpc\grpc-js\build\src\load-balancer-pick-first.js:421:54)
    at ChildLoadBalancerHandler.updateAddressList (D:\Work\Development\NodeJS\wechaty-getting-started\node_modules\@grpc\grpc-js\build\src\load-balancer-child-handler.js:115:23)
    at onSuccessfulResolution (D:\Work\Development\NodeJS\wechaty-getting-started\node_modules\@grpc\grpc-js\build\src\resolving-load-balancer.js:221:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:85:22) uncaughtException
12:17:30 ERR Config ###########################

**Comment by su-chang** [comment]
请参考 https://github.com/wechaty/puppet-supports/issues/364

**Comment by luyulong-em** [comment]
我执行的时候也发生了这个问题,后面排查是因为 @grpc/grpc-js1.9.15 之后的版本 变化导致的  npm install @grpc/grpc-js@1.9.15就解决了
