### ISSUE TITLE
[BUG]WorkPro: 发送silk文件偶尔失败

### ISSUE THREAD

**Issue by seabornlee** [wechaty/puppet-service-providers#535]
```
Error in text-to-speech process: Error: 13 INTERNAL: WorkproErrorCode: 23060, processSendMsgRsp(7881301942925180) contentType: Unknown send message failed! cgi error code: (-1800002) message: .
    at callErrorFromStatus (/Users/seabornlee/Documents/github/kzy/digital-kzy/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/Users/seabornlee/Documents/github/kzy/digital-kzy/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/Users/seabornlee/Documents/github/kzy/digital-kzy/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/Users/seabornlee/Documents/github/kzy/digital-kzy/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /Users/seabornlee/Documents/github/kzy/digital-kzy/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/Users/seabornlee/Documents/github/kzy/digital-kzy/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
    at ServiceClientImpl.messageSendFile (/Users/seabornlee/Documents/github/kzy/digital-kzy/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at node:internal/util:364:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:350:12)
    at PuppetService.messageSendFile (file:///Users/seabornlee/Documents/github/kzy/digital-kzy/node_modules/@juzi/wechaty-puppet-service/dist/esm/src/client/puppet-service.js:1052:44)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///Users/seabornlee/Documents/github/kzy/digital-kzy/node_modules/@juzi/wechaty/dist/esm/src/sayable/deliver-sayable.js:25:17
    at async WechatifiedUserClass.say (file:///Users/seabornlee/Documents/github/kzy/digital-kzy/node_modules/@juzi/wechaty/dist/esm/src/user-modules/contact.js:306:23)
    at async NewMessageHandler.handle (file:///Users/seabornlee/Documents/github/kzy/digital-kzy/handlers/new-message-handler.js:67:7) {
  code: 13,
  details: 'WorkproErrorCode: 23060, processSendMsgRsp(7881301942925180) contentType: Unknown send message failed! cgi error code: (-1800002) message: .',
  metadata: Metadata {
    internalRepr: Map(3) {
      'content-type' => [Array],
      'date' => [Array],
      'authorization' => [Array]
    },
    options: {}
  }
}
```

**Comment by hcfw007** [comment]
这种属于发送太多了企微不让发了。
