### ISSUE TITLE
[BUG]WorkPro: 服务一直 StarterBot Starter Bot Started. 

### ISSUE THREAD

**Issue by mustcarrayout** [wechaty/puppet-service-providers#577]
## 问题

服务跑起来了，但是一直`09:12:43 INFO StarterBot Starter Bot Started.`，没下文了。而且服务监听网站，一直显示`离线`
![image](https://github.com/user-attachments/assets/9fe2f165-c137-46bd-9c72-7cdb38aed4c3)

## os

`mac` 

## cmd

```
export WECHATY_LOG=verbose
export WECHATY_PUPPET=wechaty-puppet-wechat

export WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true
export WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com

npm start

```

## 运行日志

```
9:12:28 VERB GrpcManager initClient() ... done  
09:12:28 VERB GrpcManager start() initializing client ... done  
09:12:28 VERB GrpcManager start() starting stream ...  
09:12:28 VERB GrpcManager startStream()  
09:12:28 VERB GrpcManager startStream() grpc -> event() ...  
09:12:28 VERB GrpcManager startStream() grpc -> event() ... done  
09:12:28 VERB GrpcManager startStream() grpc -> event peeking data or timeout ...  
09:12:28 ERR Config ###########################  
09:12:28 ERR Config Wechaty uncaughtException: TypeError: Cannot use 'in' operator to search for 'port' in undefined  
    at isTcpSubchannelAddress (/Users/lihe/workspace/getting-started/node_modules/@grpc/grpc-js/src/subchannel-address.ts:40:16)  
    at subchannelAddressToString (/Users/lihe/workspace/getting-started/node_modules/@grpc/grpc-js/src/subchannel-address.ts:65:7)  
    at /Users/lihe/workspace/getting-started/node_modules/@grpc/grpc-js/src/load-balancer-pick-first.ts:505:90  
    at Array.map (<anonymous>)  
    at PickFirstLoadBalancer.updateAddressList (/Users/lihe/workspace/getting-started/node_modules/@grpc/grpc-js/src/load-balancer-pick-first.ts:505:50)  
    at ChildLoadBalancerHandler.updateAddressList (/Users/lihe/workspace/getting-started/node_modules/@grpc/grpc-js/src/load-balancer-child-handler.ts:137:19)  
    at onSuccessfulResolution (/Users/lihe/workspace/getting-started/node_modules/@grpc/grpc-js/src/resolving-load-balancer.ts:302:34)  
    at processTicksAndRejections (node:internal/process/task_queues:85:22) uncaughtException  
09:12:28 ERR Config ###########################  
09:12:33 VERB GrpcManager startStream() grpc -> event peeking data or timeout ... timeout  
09:12:33 VERB GrpcManager startStream() grpc -> event peeking data or timeout ... data peeked  
09:12:33 VERB GrpcManager startStream() initializing event stream ...  
09:12:33 VERB GrpcManager startStream() initializing event stream ... done  
09:12:33 VERB GrpcManager startStream() ... done  
09:12:33 VERB GrpcManager start() starting stream ... done  
09:12:33 VERB GrpcManager start() calling grpc server: start() ...  
09:12:43 WARN WechatyPuppetMixin start() starting puppet ... timeout  
09:12:43 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetService>(ding-dong-bot)  
09:12:43 VERB ServiceCtl<Wechaty> start() super.start() ... done  
09:12:43 VERB ServiceCtl<Wechaty> start() this.onStart() ...  
09:12:43 VERB Wechaty onStart()  
09:12:43 VERB Wechaty <wechaty-puppet-service>(ding-dong-bot) onStart() v1.20.2 is starting...  
09:12:43 VERB Wechaty id: c164cb9e-b26d-425d-99de-f6b99406a933  
09:12:43 VERB Wechaty onStart() ... done  
09:12:43 VERB ServiceCtl<Wechaty> start() this.onStart() ... done  
09:12:43 VERB StateSwitch <Wechaty> active(true) <- (pending)  
09:12:43 VERB ServiceCtl<Wechaty> start() ... done  
09:12:43 INFO StarterBot Starter Bot Started.  
```

**Comment by SagarChandra07** [comment]
download

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme
I put the necessary dlls in the archive

**Comment by mustcarrayout** [comment]
> download
> 
> https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA Archive password: changeme I put the necessary dlls in the archive

I run in MAC OS,not windows
