### ISSUE TITLE
[BUG]WorkPro: Cannot login after scanning. 3 tokens down only 1 left that works.

### ISSUE THREAD

**Issue by lilyd-code** [wechaty/puppet-service-providers#582]
**Describe the bug**

Scan is not being registered after user scans. No login event is provided

**Info**

<img width="1439" alt="Screenshot 2024-09-30 at 11 17 36 AM" src="https://github.com/user-attachments/assets/1b3a288c-7096-4f42-84d1-d64621fe9540">

 - Platform[e.g. Windows/Mac/Linux]: Linux
 - Runtime version[e.g. node/JAVA]: node
 - Wechaty version: "@juzi/wechaty": "^1.0.65"
 - Wechaty Puppet version:  "@juzi/wechaty-puppet": "^1.0.61",
<img width="546" alt="Screenshot 2024-09-30 at 11 18 15 AM" src="https://github.com/user-attachments/assets/38952f37-1405-4497-aa9a-7f9d7d0ebf0e">

**To Reproduce**

1. 
<img width="528" alt="Screenshot 2024-09-30 at 11 19 37 AM" src="https://github.com/user-attachments/assets/901f1c61-b26f-437c-80a1-8aa7a83bcbe2">
2. Scan the QR code
3. (Optional) Sometimes we get this message on the Wecom user's phone:
![image](https://github.com/user-attachments/assets/bb590a7f-54b2-4724-862e-f744bbd0fafe)
4. (Optional) We enter the verification code using the new @juzi/Wechaty
<img width="1374" alt="Screenshot 2024-09-30 at 11 23 52 AM" src="https://github.com/user-attachments/assets/bc31bbaa-f8e4-41d2-9877-f2e1f803f4a4">
5. We only receive these messages and nothing about logging in
<img width="739" alt="Screenshot 2024-09-30 at 11 24 39 AM" src="https://github.com/user-attachments/assets/19a07007-9c53-476d-8fc6-65241ed056fe">

**Expected behavior**

There should be a login event, that logs the user has logged in

** Screenshots**
<img width="750" alt="Screenshot 2024-09-30 at 11 28 52 AM" src="https://github.com/user-attachments/assets/0b4e534a-f3d9-4667-9d5a-7d3782cc8c3f">

**Additional context**

It started with one account, then the two other accounts needed logging and everything stopped working. Only one account works now because it hasn't been logged out.

**Comment by hcfw007** [comment]
please provide the last 6 characters of your token and the time you scan.

**Comment by lilyd-code** [comment]
Hi hcfw, here's the last character of our tokens we tried to scan 6 minutes ago and it didn't work.
`a8d891`
They get logged in but WeChaty doesn't send a login event:
![image](https://github.com/user-attachments/assets/c0e5da5f-1f26-49b0-8b9d-5245b16bcbc5)

We tried it twice we're in Eastern Timezone.
![Screenshot 2024-10-01 at 9 54 10 AM](https://github.com/user-attachments/assets/f94686b7-0416-42dc-bcef-1379643ded07)

**Comment by lilyd-code** [comment]
also our two other tokens that weren't working for scan started scanning again but not the one mentioned above

**Comment by hcfw007** [comment]
Got it. I'll look into it. Sorry it's vacation season now the response might be delayed.

**Comment by hcfw007** [comment]
![image](https://github.com/user-attachments/assets/303ce235-dc03-4917-9adb-8840001347c7)

![image](https://github.com/user-attachments/assets/19063f68-365f-4291-9ee9-bba30f2e2888)


In Sep 25th, Tencent published Wecom 4.1.30. Usually it won't force you to upgrade the version of your windows wecom (which is the platform workpro is working), however we found that since Sep 30th, Tencent is randomly picking some of the accounts to do so.

We are working on adapting the new version now, and will upgrade our server as soon is it's ready.

**Comment by lilyd-code** [comment]
Thank you, would it be possible to have a temporary token while this fix is being made? Token seems to be deactivated now
![Screenshot 2024-10-03 at 1 37 55 PM](https://github.com/user-attachments/assets/958735a5-7a11-450a-94d9-e3d6602abe33)

**Comment by Lyq0055** [comment]
> Hi hcfw, here's the last character of our tokens we tried to scan 6 minutes ago and it didn't work. `a8d891` They get logged in but WeChaty doesn't send a login event: ![image](https://private-user-images.githubusercontent.com/157885411/372496195-c0e5da5f-1f26-49b0-8b9d-5245b16bcbc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjgwMzgsIm5iZiI6MTcyODI2NzczOCwicGF0aCI6Ii8xNTc4ODU0MTEvMzcyNDk2MTk1LWMwZTVkYTVmLTFmMjYtNDliMC04YjlkLTUyNDViMTZiY2JjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwMjIyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmNiZGYwZGEyMjRhNjQyYjkxOWVkNzM5M2M0ZDI1ZGQ1MzQyODhkOTgwY2JiNmVlYzM3ODI5MTMyNjdkZjRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hxYoRwFa6KoA2g9zAV6rBl1bn-QXyd8z2yctpDVZqq8)
> 
> We tried it twice we're in Eastern Timezone. ![Screenshot 2024-10-01 at 9 54 10 AM](https://private-user-images.githubusercontent.com/157885411/372497216-f94686b7-0416-42dc-bcef-1379643ded07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjgwMzgsIm5iZiI6MTcyODI2NzczOCwicGF0aCI6Ii8xNTc4ODU0MTEvMzcyNDk3MjE2LWY5NDY4NmI3LTA0MTYtNDJkYy1iY2VmLTEzNzk2NDNkZWQwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwMjIyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmFhNDY5MWQ5NGJhYWFiMDRjYzQwYWVmMjRkNTNkMGI3NTYxNWMzNWMzZDQ1MzlmZTVhODk0NmNiNjQwNjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fhZj90GUgTBIF58rlYgDIGN58DdTG8QwviTcNmCjAw4)

Has it been resolved? I've also encountered the same issue.

**Comment by kayorlian** [comment]
我们也遇到了

**Comment by lilyd-code** [comment]
> > Hi hcfw, here's the last character of our tokens we tried to scan 6 minutes ago and it didn't work. `a8d891` They get logged in but WeChaty doesn't send a login event: ![image](https://private-user-images.githubusercontent.com/157885411/372496195-c0e5da5f-1f26-49b0-8b9d-5245b16bcbc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjgwMzgsIm5iZiI6MTcyODI2NzczOCwicGF0aCI6Ii8xNTc4ODU0MTEvMzcyNDk2MTk1LWMwZTVkYTVmLTFmMjYtNDliMC04YjlkLTUyNDViMTZiY2JjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwMjIyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmNiZGYwZGEyMjRhNjQyYjkxOWVkNzM5M2M0ZDI1ZGQ1MzQyODhkOTgwY2JiNmVlYzM3ODI5MTMyNjdkZjRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hxYoRwFa6KoA2g9zAV6rBl1bn-QXyd8z2yctpDVZqq8)
> > We tried it twice we're in Eastern Timezone. ![Screenshot 2024-10-01 at 9 54 10 AM](https://private-user-images.githubusercontent.com/157885411/372497216-f94686b7-0416-42dc-bcef-1379643ded07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjgwMzgsIm5iZiI6MTcyODI2NzczOCwicGF0aCI6Ii8xNTc4ODU0MTEvMzcyNDk3MjE2LWY5NDY4NmI3LTA0MTYtNDJkYy1iY2VmLTEzNzk2NDNkZWQwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwMjIyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmFhNDY5MWQ5NGJhYWFiMDRjYzQwYWVmMjRkNTNkMGI3NTYxNWMzNWMzZDQ1MzlmZTVhODk0NmNiNjQwNjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fhZj90GUgTBIF58rlYgDIGN58DdTG8QwviTcNmCjAw4)
> 
> Has it been resolved? I've also encountered the same issue.

Not yet. we are still waiting for the resolution.

**Comment by kayorlian** [comment]
没有过渡性方案吗？

**Comment by IQZZ020501** [comment]
> > > 嗨 hcfw，这是我们 6 分钟前尝试扫描的令牌的最后一个字符，但没有成功。`a8d891`他们登录了，但微信没有发送登录事件：
> > > 我们尝试了两次，因为我们在东部时区。![图像](https://private-user-images.githubusercontent.com/157885411/372496195-c0e5da5f-1f26-49b0-8b9d-5245b16bcbc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjgwMzgsIm5iZiI6MTcyODI2NzczOCwicGF0aCI6Ii8xNTc4ODU0MTEvMzcyNDk2MTk1LWMwZTVkYTVmLTFmMjYtNDliMC04YjlkLTUyNDViMTZiY2JjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwMjIyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmNiZGYwZGEyMjRhNjQyYjkxOWVkNzM5M2M0ZDI1ZGQ1MzQyODhkOTgwY2JiNmVlYzM3ODI5MTMyNjdkZjRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hxYoRwFa6KoA2g9zAV6rBl1bn-QXyd8z2yctpDVZqq8)![截图于 2024-10-01 上午 9 点 54 分](https://private-user-images.githubusercontent.com/157885411/372497216-f94686b7-0416-42dc-bcef-1379643ded07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjgwMzgsIm5iZiI6MTcyODI2NzczOCwicGF0aCI6Ii8xNTc4ODU0MTEvMzcyNDk3MjE2LWY5NDY4NmI3LTA0MTYtNDJkYy1iY2VmLTEzNzk2NDNkZWQwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwMjIyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmFhNDY5MWQ5NGJhYWFiMDRjYzQwYWVmMjRkNTNkMGI3NTYxNWMzNWMzZDQ1MzlmZTVhODk0NmNiNjQwNjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fhZj90GUgTBIF58rlYgDIGN58DdTG8QwviTcNmCjAw4)
> > 
> > 
> > 解决了吗？我也遇到了同样的问题。
> 
> 还没有。我们还在等待解决方案。

你好，目前解决了吗

**Comment by lilyd-code** [comment]
还没有解决，还在等。
Hi Nick~请问更新进度大概什么时候可以完成?
@hcfw007

**Comment by lilyd-code** [comment]
Our token doesn't work anymore, here is the error in our logs:

`    at Object.onReceiveStatus (/home/ubuntu/polaris/node_modules/@grpc/grpc-js/build/src/
client-interceptors.js:323:181)
    at /home/ubuntu/polaris/node_modules/@grpc/grpc-js/build/src/resolving-call.js:93:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/home/ubuntu/polaris/node_modules/@grpc/grpc-j
s/build/src/client.js:160:34)
    at ServiceClientImpl.start (/home/ubuntu/polaris/node_modules/@grpc/grpc-js/build/src
/make-client.js:105:19)
    at node:internal/util:364:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:350:12)
    at GrpcManager.start (/home/ubuntu/polaris/node_modules/@juzi/wechaty/node_modules/@juzi/wechaty-puppet-service/dist/cjs/src/client/grpc-manager.js:135:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetService.onStart (/home/ubuntu/polaris/node_modules/@juzi/wechaty/node_modules/@juzi/wechaty-puppet-service/dist/cjs/src/client/puppet-service.js:134:9)
    at async PuppetService.start (/home/ubuntu/polaris/node_modules/state-switch/dist/cjs/src/service-ctl/service-ctl.js:65:17)
    at async PuppetService.start (/home/ubuntu/polaris/node_modules/@juzi/wechaty/node_modules/@juzi/wechaty-puppet/dist/cjs/src/mixins/service-mixin.js:21:13) {
  code: 14,
 'Wechaty service discovery / resolution failed for target wechaty://token-service-discovery-test.juzibot.com/***********************************************: token "***********************************************" does not exist'`

**Comment by hcfw007** [comment]
现在workpro已经全量更新到企微新版本了，可以尝试登录，如果不行可以联系销售帮你重启token试试。
