### ISSUE TITLE
[BUG]WorkPro: bot.Room.create 报错 Error: not ready

### ISSUE THREAD

**Issue by edk24** [wechaty/puppet-service-providers#593]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

code

```javascript
// 创建群聊
      app.post('/room/create', async (req, res) => {
          try {
              const {
                  wxid,
                  room_name,
                  say_hi
              } = req.body
              const people = await bot.Contact.find({
                  id: wxid
              })
              if (!people) {
                  throw new Error('找不到联系人 "' + wxid + '"')
              }

              const room = await bot.Room.create([people], room_name)
              if (!room) {
                  throw new Error('创建群聊失败')
              }

              if (say_hi) {
                  room.say(say_hi)
              }
              console.log('room created:', room)

              const avatar = room.avatar()

              res.send({
                  code: 0,
                  data: {
                      id: room.id,
                      topic: await room.topic(),
                      ownerId: room.owner()?.id,
                      avatar: avatar ? await (await avatar).toBase64() : ''
                  }
              })
          } catch (e:any) {
              res.send({code: 1, message: e.message})
              /*
                遇到异常,  e.message === not ready
                ====== Error: not ready
                  at WechatifiedUserClass.topic (file:///www/wwwroot/wechat-bot/node_modules/@juzi/wechaty/dist/esm/src/user-modules/room.js:739:19)
                  at file:///www/wwwroot/wechat-bot/src/main.ts:173:39
                  at Generator.next (<anonymous>)
                  at fulfilled (file:///www/wwwroot/wechat-bot/src/main.ts:4:58)
                  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              */
          }
      })
```

**Describe the bug**

当发起请求, 提供wxid创建群聊时, 总是会返回 "not ready", 但是群聊会正常创建.   

问题是我拿不到 "群的信息, roomid 等"

**Info**

 - Platform[e.g. Windows/Mac/Linux]: Linux
 - Runtime version[e.g. node/JAVA]: Node
 - Wechaty version: 
 - Wechaty Puppet version: 

```bash
├── @grpc/grpc-js@1.8.12
├── @juzi/wechaty-puppet-service@1.0.101
├── @juzi/wechaty-puppet@1.0.92
├── @juzi/wechaty@1.0.100
├── @types/body-parser@1.19.5
├── @types/express@4.17.21
├── @types/node@22.8.2
├── @types/qrcode-terminal@0.12.2
├── body-parser@1.20.3
├── cross-env@7.0.3
├── express@4.21.1
├── file-box@1.5.5
├── qrcode-terminal@0.12.0
├── ts-node@10.9.2
└── typescript@5.6.3
```

**To Reproduce**

1. 提供wxid创建群聊就会遇到, 之前一直没有

** 完整代码**

```typescript
import { ScanStatus, WechatyBuilder, WechatyOptions, log } from '@juzi/wechaty'
import { FriendshipType } from '@juzi/wechaty-puppet/dist/esm/src/schemas/friendship'
import qrcodeTerminal from 'qrcode-terminal'
import readline from 'readline'
import { FileBox } from 'file-box'
import express from 'express';
import bodyParser from 'body-parser';


/** 
 * 创建一个 express 应用
 */
const app = express()
const port = 3001
app.use(bodyParser.json({ limit: '1mb' }))
app.use(bodyParser.urlencoded({
    extended: true
}))

let read = readline.createInterface({
    input: process.stdin,
    output: process.stdout
})

const config: WechatyOptions = {
    name: 'ding-dong-bot',
    puppet: '@juzi/wechaty-puppet-service',
    puppetOptions: {
        token: 'puppet_workpro_***********b4568b5',
        authority: 'token-service-discovery-test.juzibot.com',
        timeoutSeconds: 1 * 60,
        tls: {
            disable: true
        },
    },
}

const store = {
    qrcodeKey: 'qrcodeKey'
}

const bot = WechatyBuilder.build(config)

function enterVerifyCode() {
    return new Promise<string>((resolve) => {
        read.question('请输入验证码：', (verifyCode:string) => {
            read.close()
            resolve(verifyCode.trim())
        })
    })
}

function getQrcodeKey(qrcode: string) {
    // https://wx.work.weixin.qq.com/cgi-bin/crtx_auth?key=6A31D2E24E243D751DAC6C8536E5FA56&wx=1
    const match = qrcode.match(/key=(\w+)&/)
    if (match) {
        return match[1]
    }
    return ''
}

/**
 * 扫码
 */
bot.on('scan', async (qrcode, status) => {
    console.log(`qrcode: ${qrcode}, status: ${status}`)
    if (status === ScanStatus.Waiting || status === ScanStatus.Timeout) {
        store.qrcodeKey = getQrcodeKey(qrcode) || ''
        log.info('Key', store.qrcodeKey)

        qrcodeTerminal.generate(qrcode, { small: true })  // show qrcode on console
    } else {
        log.info('StarterBot', 'onScan: %s(%s)', ScanStatus[status], status)
    }
})

/**
 * 验证码确认
 */
bot.on('verify-code', async (id, message, scene, status) => {
    log.info('verifyCode', `id: ${id}, message: ${message}, scene: ${scene}, status: ${status}`)

    if (status === 1 && scene === 1 && id === store.qrcodeKey) {
        try {
            const code = await enterVerifyCode()
            bot.enterVerifyCode(id, code)
        } catch (e:any) {
            console.log(e.message)
        }
        
    }
})

/**
 * 登录成功
 */
bot.on('login', async (user) => {
    console.log(`User ${user} logged in`)
})

/**
 * 好友请求
 */
bot.on('friendship', async (friendship) => {
    try {
        
        const type = friendship.type()
        if (type.toString() == "2") { // 好友请求 FriendshipType.Receive
            console.log(`收到好友请求`, friendship.type())
            await friendship.accept()
        } else if (type.toString() == "1") { // 好友确认 FriendshipType.Confirm
            console.log(`好友关系已建立`)
            const contact = friendship.contact()
            friendship.contact().say(`您的绑定编号是: ${contact.id}, 请复制这段内容到小程序中建立绑定关系`)
        } else if (type.toString() == "4") { // 删除好友 FriendshipType.Delete
            console.log(`删除好友, 好友关系解绑`)
        } else if (type.toString() == "5") { // 好友被删除 FriendshipType.Removed
            console.log(`好友被删除, 好友关系解绑`, friendship.contact().id)
        }
       
    } catch (e) {
        log.error('friendship', e)
    }
})

bot.on('message', async (message) => {
    console.log(`Message: ${message}`)
})


bot.start()
    .then(() => {
        console.log('Bot started.')

        // 空白页
        app.get('/', (req, res) => {
            res.send('Hello World!')
        })

        // 创建群聊
        app.post('/room/create', async (req, res) => {
            try {
                const {
                    wxid,
                    room_name,
                    say_hi
                } = req.body
                const people = await bot.Contact.find({
                    id: wxid
                })
                if (!people) {
                    throw new Error('找不到联系人 "' + wxid + '"')
                }

                const room = await bot.Room.create([people], room_name)
                if (!room) {
                    throw new Error('创建群聊失败')
                }

                if (say_hi) {
                    room.say(say_hi)
                }
                console.log('room created:', room)

                const avatar = room.avatar()

                res.send({
                    code: 0,
                    data: {
                        id: room.id,
                        topic: await room.topic(),
                        ownerId: room.owner()?.id,
                        avatar: avatar ? await (await avatar).toBase64() : ''
                    }
                })
            } catch (e:any) {
                res.send({code: 1, message: e.message})
            }
        })

        app.listen(port, () => {
            console.log(`Http Listening at http://localhost:${port}`)
        })
    })
    .catch((e) => {
        log.error('StarterBot', e)
    })
```

**Comment by edk24** [comment]
没人解决吗?

**Comment by IQZZ020501** [comment]
> 没人解决吗?

会不会是因为群聊没创建好你就获取了，创建群聊下面sellp几秒试试嘞

**Comment by hcfw007** [comment]
加上一条 await room.sync()
```ts
const room = await bot.Room.create([people], room_name)
await room.sync()
```

**Comment by edk24** [comment]
> 加上一条 await room.sync()
> 
> ```ts
> const room = await bot.Room.create([people], room_name)
> await room.sync()
> ```

好的, 我试试

**Comment by edk24** [comment]
> > 没人解决吗?
> 
> 会不会是因为群聊没创建好你就获取了，创建群聊下面sellp几秒试试嘞

好的,我尝试一下

**Comment by edk24** [comment]
@hcfw007 @IQZZ020501 

有效, 感谢🙏

没想过得到的 room 还需要 sync 等待一下, 一直是想着我已经 await 了, 应该没问题 😓

**Comment by edk24** [comment]
@hcfw007 @IQZZ020501

有效, 感谢🙏

没想过得到的 room 还需要 sync 等待一下, 一直是想着我已经 await 了, 应该没问题 😓

**Comment by huan** [comment]
> 加上一条 await room.sync()
> 
> ```ts
> const room = await bot.Room.create([people], room_name)
> await room.sync()
> ```

If this workaround can fix the problem, then it's a bug of the `Room.create`: it should guarantee the returned `Room` instance already has `sync-ed`. This means the `room.sync()` should be done inside the `Room.create`.

I would love to accept a PR to fix that.
