### ISSUE TITLE
[BUG]WorkPro:

### ISSUE THREAD

**Issue by Emirateyang** [wechaty/puppet-service-providers#598]
Please make sure you have read the [Wechaty Puppet Service: WorkPro](https://wechaty.js.org/docs/puppet-services/workpro) from Wechaty Official Website before you continue writing this issue.

**IMPORTANT**

DO NOT post your token in the issue. If we need to investigate the behavior of certain token, we will provide a private contact route.

**Describe the bug**

Can not talk in room, when message send bot will quit with error
btw, I use docker, the docker image will exist when the error occur.
I am the paid user, and my system is out of service

**Info**

 - Platform[e.g. Windows/Mac/Linux]: 
   Linux
 - Runtime version[e.g. node/JAVA]:
 - Wechaty version: 
  1.0.99
 - Wechaty Puppet version: 
  1.0.90

**To Reproduce**

**Expected behavior**

when talk in room, an error occur when message received, and bot will quit

**Screenshots**

03:08:15 INFO PuppetService onStart() ... done
03:08:30 INFO PuppetService received grpc event EVENT_TYPE_READY on Fri Nov 01 2024 03:08:30 GMT+0000 (Coordinated Universal Time), content: "{\"data\":\"data ready\"}", seq: 0, timestamp: 1730430510193
03:08:53 INFO PuppetService received grpc event EVENT_TYPE_MESSAGE on Fri Nov 01 2024 03:08:53 GMT+0000 (Coordinated Universal Time), content: "{\"messageId\":\"d94db32163a13039437e75e60c5ba3e6\"}", seq: 64, timestamp: 1730430533678
03:08:53 WARN last event was 86320.3 seconds ago, will not request event cache 
/usr/src/wechat-com-bot/node_modules/@juzi/wechaty/src/pure-functions/is-template-string-array.ts:2
  return Array.isArray(tsa.raw) && Array.isArray(tsa)
                           ^
TypeError: Cannot read properties of undefined (reading 'raw')
    at isTemplateStringArray (/usr/src/wechat-com-bot/node_modules/@juzi/wechaty/src/pure-functions/is-template-string-array.ts:2:28)
    at WechatifiedUserClass.say (/usr/src/wechat-com-bot/node_modules/@juzi/wechaty/src/user-modules/room.ts:511:30)
    at /usr/src/wechat-com-bot/index.ts:235:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Additional context**

**Comment by corrosive4354** [comment]
Brother, I saw you guys are using docker,
I think you can try the tool [servbay](https://servbay.com), it is more professional on Mac

**Comment by Emirateyang** [comment]
@hcfw007 能帮我看看么

**Comment by hcfw007** [comment]
如果还需要的话，请升级到最新版本试试。
